### ISSUE TITLE
Intermittent failure in test_worker.py::test_compute

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#221]
We have an intermittent failure in master.  I've been guiltily pressing the reload button on travis.ci to get PRs to be green.  I suspect that this is either a serialization issue or wonkiness with zmq.  Some fairly tediious testing against travis.ci suggests that the blocking line is this the `router.send_multipart` call in that test.

http://stackoverflow.com/questions/30271066/what-might-cause-a-zmq-router-socket-to-block

**Comment by cowlicks** [comment]
link to travis-ci failing on this
https://travis-ci.org/ContinuumIO/dask/jobs/63043536#L776
