### ISSUE TITLE
Scheduler-Worker handshake should verify discoverability

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#235]
When a worker connects to a scheduler it sends a hostname on which other workers can reach it

1.   Scheduler starts up
2.   Worker A connects to scheduler, says that it can be reached by other workers at `tcp://A:5000`
3.   Worker B connects to scheduler, says that it can be reached by other workers at `tcp://B:5000`
4.   Scheduler tells worker B to get data from worker A and sends worker B worker A' address, `tcp://A:5000`
5.   Worker B tries to connect to `tcp://A:5000` but it turns out that it isn't discoverable on the network

This can happen easily in networks in the wild and currently results in workers blocking indefinitely.  Perhaps, at the initial handshake (step 2), the scheduler should verify that the given address is publicly accessible and, if not, return an error back to A.

**Comment by minrk** [comment]
How do you determine 'publicly' accessible? Do you assume the Scheduler has the same visibility to A that B has?

**Comment by mrocklin** [comment]
That is what I was assuming above.  Presumably we could also make this check later on when we're doing the computation and we know who needs to connect to whom.  A timeout would be reasonable.  We would need to improve the scheduler's ability to stop things mid-flow, which would be good for other reasons.

Alternatively we could have some sort of verify visibility process that happens after setup but before scheduling.

**Comment by minrk** [comment]
I think checking from the Scheduler is likely to cover most cases, and it's simple enough that I wouldn't bother making explicit distributed checks before you start seeing failure cases where the schedule check is inadequate.

It is probably a good idea to add timeouts for fetches, etc. so even if workers are unreachable or go away, the failure mode is an error rather than blocking forever.

**Comment by jcrist** [comment]
`dask.distributed` no longer exists in this repository. Closing.
