### ISSUE TITLE
Improve user experience of interacting with numpy arrays

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#290]
Currently when numpy arrays interact with dask arrays we swallow errors silently, revealing them only at computation time.

```python
In [1]: import dask.array as da
In [2]: import numpy as np
In [3]: x = da.arange(15, chunks=5)
In [4]: y = np.arange(15)

In [5]: x + y
Out[5]: dask.array<x_1, shape=(15,), chunks=((5, 5, 5)), dtype=int64>

In [6]: _.compute()
ValueError: operands could not be broadcast together with shapes (5,) (15,) 
```

We should do one of the following things:

1.  Figure out automatic conversion of a numpy array into a dask array with appropriate shape to make the operation work (hard in general, maybe easy in a few key cases)
2.  Raise an informative error early on (maybe easier in the hard cases)

**Comment by cowlicks** [comment]
We might be interested in adding a `__numpy_ufunc__` method. It lets third party objects override ufuncs. More info here 

https://github.com/numpy/numpy/blob/master/doc/neps/ufunc-overrides.rst

I worked on adding this to NumPy in 2013, and continuing development on it after the Summer became unfeasible because it there was a lot of maintenance and I was in school. It's MRO is currently being discussed here: 

https://github.com/numpy/numpy/issues/5844

**Comment by cowlicks** [comment]
I don't think the state of NumPy ufunc is mature or stable enough to warrant this yet.

For now I think a simple thing to do would be to raise a `NotImplementedError` immediately instead of waiting until compute time to fail.

**Comment by shoyer** [comment]
@cowlicks  I think we'll definitely want to add `__numpy_ufunc__` once a NumPy release with it is out, if only so we don't need to write our own ufuncs like `dask.array.sin`. This will also integrate nicely with Numba's support for ufuncs on demand.

For the record, that thread is mostly about how to handle binary operation dispatching (e.g., `+`), and whether that should be independent from `__numpy_ufunc__` (e.g., `np.add`). I don't think anyone is taking issue with your design of `__numpy_ufunc__` :).

**Comment by mrocklin** [comment]
Probably this is hard to answer, but is there an ETA on a numpy release.

**Comment by shoyer** [comment]
> Probably this is hard to answer, but is there an ETA on a numpy release.

Pretty sure it's supposed to come out this summer. I'm guessing as soon as this `__numpy_ufunc__` mess is resolved (or if it's deemed unresolvable for now). @charris is in charge.

**Comment by thpfaff** [comment]
For me this problem boils down to checking whether the inputs can broadcast to a common shape and if so, if the chunk sizes can be inferred correctly for all dimensions.

For the dask arrays, we have the chunking information and we can check if they can work together. As the numpy arrays are in-memory we can choose the chunking information as we like as long as they broadcast well.

What am I missing?

**Comment by mrocklin** [comment]
Nothing.  You understand the problem completely.  Now all we have to do is implement that logic in all dask.array functions.  This might be non-trivial.

**Comment by cowlicks** [comment]
I think a good first step that broadcasts a numpy array into dask.array. We could build this incrementally too. I was thinking something like
```python
def broadcast_to_darray(np_arr, dask_arr):  # maybe we just need dask_arr.shape
    # simple scalar case
    if np.isscalarlike(np_arr):
        return da.fill(np_arr, dask_arr.shape), dask_arr
    # other cases where dask_arr.shape does not change
    # stuff where both shapes change
    raise NotImplementedError
```

Then we would stick this in `dask.array.core.elemwise`.

**Comment by shoyer** [comment]
I had some auto chunking ideas that I wrote down in another issue. I agree though that when the shape of the dask array does not change we should use the pre-existing chunks b

**Comment by cowlicks** [comment]
How would a dask.array be chunked in a dimension that is extended? For quick reference here are the numpy broadcasting docs http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

**Comment by shoyer** [comment]
See https://github.com/ContinuumIO/dask/issues/111

**Comment by shoyer** [comment]
I have a PR on this that I'm putting together -- still needs a few fixes for the tests.

**Comment by mrocklin** [comment]
Glad to hear it :)
