### ISSUE TITLE
TopK

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#317]
Parallel and out-of-core sorting is hard.  Fortunately it's not often what we want.  We often want just the top k elements.  This is quite doable.

Here are some ways of spelling this that make sense to me.  Alternatives welcome.

```python
>>> df.topk(10, 'balance')

or 

>>> df.topk(10, df.balance)

or 

>>> df.balance.topk(10)
```

This should be doable with the `apply_concat_apply` function.

After `topk` works one might extend this to also work with GroupBy objects.

```python
>>> df.groupby(df.year).topk(10, 'balance')  # top ten accounts by balance per year
```

**Comment by cpcloud** [comment]
Pandas calls this [`nlargest`](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.Series.nlargest.html) which is taken from the [`heapq` function of the same name](https://docs.python.org/2/library/heapq.html#heapq.nlargest).

**Comment by cpcloud** [comment]
We actually don't have anything like this yet:

```python
df.nlargest(5, ['balance'])
```

but I think I have this in a branch that I can push up.

**Comment by cpcloud** [comment]
pr'd this in core pandas https://github.com/pydata/pandas/pull/10393

**Comment by mrocklin** [comment]
It looks like the pandas PR has gone in.  This is up for grabs in dask.dataframe
