### ISSUE TITLE
dask.distributed debugging

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#327]
Things that would make setting up dask.distributed easier to debug

* being able to get worker and schedule PID's from the client
* being able to close workers from the client

**Comment by mrocklin** [comment]
Closing the scheduler triggers closing the workers.  Is this sufficient or is it also useful to close the workers while keeping the scheduler open?

**Comment by mrocklin** [comment]
When workers register themselves with the scheduler they currently send an empty dictionary of metadata

            self.send_to_scheduler({'function': 'register'}, {}) 

It would be good to put the PID there.  This is accessible under `Scheduler.workers`

**Comment by mrocklin** [comment]
@cowlicks what was your desired functionality for closing workers from client?  Is it sufficient to close the scheduler and have the scheduler close the workers?  In what context did this come up?

**Comment by cowlicks** [comment]
It came up when I had the cluster in a weird state. I had a single worker on a remote node connected. But wanted to destroy it so I could re-launch all  the workers and not worry about what happens with two workers on one node.

I had to ssh to the node and `kill` it after figuring out its pid.

This just came up while I was experimenting with making the anaconda-cluster plugin so it probably is not super important to our users.
