### ISSUE TITLE
Running py.test in root dask directory detects & runs something in the conda.recipe directory and fails.

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#379]

**Comment by mrocklin** [comment]
Can this be fixed with an appropriate change in a pytest conf file?

**Comment by cowlicks** [comment]
Probably, since we seem to be wedded to py.test it would probably be could to dive into to the conftest.py docs to figure this and the test skipping problem @jcrist  mentioned. There is also an annoying `import file mismatch` issue that comes up sometimes that requires deleting the *.pyc and __pycache__ files.

**Comment by mrocklin** [comment]
What is the status on this?

**Comment by jcrist** [comment]
I haven't seen any problems with test skipping anymore. I always run `py.test dask` inside the toplevel directory, and everything now works fine.

**Comment by jcrist** [comment]
Fixed by #449.
