### ISSUE TITLE
What happens when a node disappears from a dask.distributed cluster? What *should* happen?

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#380]
1. I launch a cluster with 4 nodes, one has the scheduler and client, the other 3 have a worker process running on them.

2. I kill one worker.

3. I do a simple computation with the client, and it hangs forever.
```python
import dask.array as da
da.arange(1e3, chunks=(100,)).compute()  # hangs
```

So what should happen?

The scheduler could check regularly that it has heard a heartbeat from all workers within a given amount of time. If this time is exceeded, we say the worker timedout. And un-register it with the scheduler. This will probably work fine if the cluster is not currently working on a job.

What if the cluster is computing something *while* a worker dies?

Currently my idea is: The scheduler notices a missing heartbeat, so it interrupts all workers and restarts the job.

**Comment by mrocklin** [comment]
Currently my idea is: The scheduler notices a missing heartbeat, so it interrupts all workers and restarts the job.

This sounds like a good default to start with.  We actually have all of the information necessary to only rerun the necessary jobs.  We happen to know what the worker was working on.  We also know all of the data it was holding before it died and we know the graph to recreate that data.  So we could *roll back* the execution state to include tasks to recreate all of the missing data.

This is a detail oriented but relatively straightforward problem that could probably be solved somewhat orthogonally from the dask.distributed machinery.

But again, I think that your intuition is right here that, for now, just setting things up to restart is probably good enough and tackles a big chunk of the problem.

**Comment by mrocklin** [comment]
Something that I anticipate we'll run into is long-running tasks that hold the GIL.  These will effectively kill the heartbeat during their execution.  I don't think that we should worry about them that much to start with, just something to keep in mind as a potential issue.

**Comment by mrocklin** [comment]
> This sounds like a good default to start with. We actually have all of the information necessary to only rerun the necessary jobs. We happen to know what the worker was working on. We also know all of the data it was holding before it died and we know the graph to recreate that data. So we could roll back the execution state to include tasks to recreate all of the missing data.

> This is a detail oriented but relatively straightforward problem that could probably be solved somewhat orthogonally from the dask.distributed machinery.

This is the sort of problem for which @eriknw and @jcrist have shown interest in the past.  Given a dask.async state and a list of suddenly-no-longer-available-data, produce a state that includes tasks to produce that data as well.

**Comment by eriknw** [comment]
Is something like this what you're looking for?  `calculated_keys` does not include the keys from the failed worker.
```python
def subdask(dsk, calculated_keys, desired_keys):
    calculated_keys = set(calculated_keys)
    desired_keys = set(desired_keys) - calculated_keys
    d = dict((k, v) for k, v in dsk.items() if k not in calculated_keys)
    return cull(d, desired_keys)
```
```python
In [10]: d = {'x': 1, 'y': (add, 'x', 1), 'z': (add, 'y', 1)}

In [11]: subdask(d, ['y'], ['z'])
Out[11]: {'z': (<function __main__.add>, 'y', 1)}
```

**Comment by mrocklin** [comment]
The state that needs to be updated looks like this 

```python
>>> dsk = {'x': 1, 'y': 2, 'z': (inc, 'x'), 'w': (add, 'z', 'y')}
>>> pprint.pprint(start_state_from_dask(dsk)) # doctest: +NORMALIZE_WHITESPACE
{'cache': {'x': 1, 'y': 2},
 'dependencies': {'w': set(['y', 'z']),
                  'x': set([]),
                  'y': set([]),
                  'z': set(['x'])},
 'dependents': {'w': set([]),
                'x': set(['z']),
                'y': set(['w']),
                'z': set(['w'])},
 'finished': set([]),
 'ready': ['z'],
 'ready-set': set(['z']),
 'released': set([]),
 'running': set([]),
 'waiting': {'w': set(['z'])},
 'waiting_data': {'x': set(['z']),
                  'y': set(['w']),
                  'z': set(['w'])}}
```

Actually, only the variables `finished` and after.  This state tracks what still needs to happen in the computation.  It is described here https://github.com/ContinuumIO/dask/blob/master/dask/async.py#L28-L85
