### ISSUE TITLE
DataFrame map/apply

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#418]
People often want to apply a Python function across many rows in a dataframe.  What is the right API for this?  `DataFrame.apply` makes guarantees that we can't meet.  Do we make a `DataFrame.map` function?  If so what is the interface?  Do we accept both functions that take a tuple as well as variadic functions? (not hard to do, `dask.bag` does this)

**Comment by limx0** [comment]
+1 would love to have a df.apply(axis=0)

**Comment by StuartAxelOwen** [comment]
IMO, pandas' `DataFrame.apply` does not apply, it maps - and even then the default of `axis=1` is confusing.   I think adding both would help - you could use `DataFrame.map` to do it the correct way, and `DataFrame.apply` to keep compatibility with pandas and reduce migration costs for existing codebases.
