### ISSUE TITLE
Solving linear systems with symmetric positive definite matrices

### ISSUE THREAD

**Issue by leouieda** [blaze/dask#476]
I do a lot of work with linear and non-linear least squares problems that involve large matrices. Fortunately these matrices are almost always symmetric positive definite, so there are ways of doing it more efficiently by exploring that's symmetry. It would be great be able to do this out-of-core. This would enable the whole process to be done streaming with dask arrays.

 I'm not an expert in linear algebra so I can't help much with the specifics. Some pointers to algorithms would be great.

**Comment by mrocklin** [comment]
What functions for combinations of functions do you use now within `numpy/scipy`?  Can you provide a small example with fake/artifiicial data and an expected result?

**Comment by leouieda** [comment]
@mrocklin usually only `dot` and `solve`. Sometimes I need to extract the diagonal of a matrix, but that as be done easily through fancy indexing. Only thing missing really is `solve`. I'll try to come up with a simple example and post a link here.

**Comment by cowlicks** [comment]
My first naive approach to `solve` would be for some system of `n` equations with `n` variables. You would have a matrix equation like `A = Ib` where `A`, and `I` are `n x n` matrices, `b` is a vector of length `n`. You could do something like:
```python
U, s, V = dask.array.svd(A)
out = U * b * V
```
Does that sound right?

**Comment by mrocklin** [comment]
We would probably want to find a stable blocked algorithm for blocked cholesky decomposition

**Comment by mrocklin** [comment]
My expertise here is limited.  This probably requires doing a bit of research first.

**Comment by leouieda** [comment]
@cowlicks the SVD solution might work but it's not very efficient if you want an exact solution. 

@mrocklin Cholesky would be great. I'll do some digging around to see if I can find any references for this. A conjugate gradient might also be good for an approximate solution. It seems straight forward to implement and probably won't require custom building custom graphs.

**Comment by mrocklin** [comment]
This might be an accessible read on this topic. https://math.berkeley.edu/~strain/128b.S15/van.de.geijn.cholesky.notes.pdf

**Comment by jcrist** [comment]
We now have a much larger set of linear algebra operations:

- `da.linalg.solve`: #938
- `da.linalg.lu`: #885
- `da.linalg.lstsq`: #942 
- `da.linalg.cholesky`: #940 

These seem to cover the use case described above. Closing.
