### ISSUE TITLE
dask.array flatten and reshape

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#570]
The numpy method `flatten` can be used to reshape an n-dimensional array into a one-dimensional array.

```python
In [1]: import numpy as np

In [2]: x = np.array([[1, 2, 3], [4, 5, 6]])

In [3]: x
Out[3]: 
array([[1, 2, 3],
       [4, 5, 6]])

In [4]: x.flatten()
Out[4]: array([1, 2, 3, 4, 5, 6])
```

We could add such a method onto `dask.array.Array` if we are willing to give up caring about byte order entirely.  

This might be a good on-ramp issue.  It requires applying the `flatten` method onto each block, creating a new flattened dictionary, manipulating `chunks`, etc..  Furthermore we could use this as a learning opportunity to improve documentation on how to [extend dask array](http://dask.pydata.org/en/latest/array-extend.html).

cc @kwmsmith

**Comment by shoyer** [comment]
The natural generalization of `flatten` is `reshape`, which could also be useful.

At the very least, it would be nice to have support for reshaping *within blocks*. For example, if I have an array with shape `(100, 100, ...)` and blocks `(100, 100, 10)`, I should be able to reshape it to `(10000, ...)`. For example, this would let us generalize point-indexing (https://github.com/ContinuumIO/dask/pull/439) to fully general vectorized indexing.

**Comment by shoyer** [comment]
@cowlicks notes that my use case (reshaping within blocks) could be solved by `map_blocks`. This is almost, but not quite true -- `map_blocks` can't handle changed array dimensions (see #263, #445).
