### ISSUE TITLE
DataFrame tests sensitive to order

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#588]
On Windows I get an error in `test_arithmetics` that reduces down to the fact that these two series don't compare as equal

```python
pd.Series([1, 2], index=['a', 'a])
pd.Series([2, 1], index=['a', 'a])
```

That is, our code seems to be correct but the tests are perhaps overly strict in this case.

**Comment by sinhrks** [comment]
Added sort logic (value -> index) before comparison in #630. I believe it can solve this issue.
