### ISSUE TITLE
investigate using dask in sklearn's grid search and pipelines

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#595]
cc @amueller

My understanding  is that sklearn is using joblib in for pararllelizing their pipelines and gridsearches, but there is room for improvement.

For example in the pipelines, when the last part of a pipeline is changed, the entire thing is recomputed. But the results from the first part of the pipeline could be reused, but they are not.

**Comment by amueller** [comment]
Exactly.
The overall process of the "pipeline" is a bit more complex than it sounds from that, but that is the gist.
Do you think this can be done using the imperative interface or should we try writing the graph directly?

I am not sure which part we need to replace for this to work. We probably need to implement dasky versions of GridSearchCV and Pipeline for a first prove of concept.

Ping @jnothman @gaelvaroquaux @ogrisel in case they are interested.

**Comment by mrocklin** [comment]
Dask.imperative and writing dictionaries directly are roughly equivalent in terms of capability.  It's just a question of style.  Internally we tend to stick to dictionaries because this allows us to specify the key names explicitly; this is useful for debugging.  However dictionaries limits the pool of potential co-developers; imperative may be better from a community standpoint.

**Comment by mrocklin** [comment]
The cross validation example at the bottom of this blogpost may be of interest http://matthewrocklin.com/blog/work/2015/07/23/Imperative/

**Comment by amueller** [comment]
I'll (try to) look into it. I'd love to write the prototypes myself, but I'm not sure I can find the time.
@cowlicks said he could look into it.

**Comment by cowlicks** [comment]
Hey @amueller, here is a naive grid search example with dask.imperative. It just takes a function, list of parameters, and key for sorting the results of the function with the parameters.
```python
from itertools import product
from dask.imperative import do
def grid_search(func, params, key=None):
    """
    >>> grid_search(lambda x, y: x + y, (range(2), range(2, 3))).compute()
    [((0, 2), 2), ((1, 2), 3)]
    """
    if key is None:
        key = lambda x: x

    do_func = do(func)
    do_sorted = do(sorted)
    results = [(p, do_func(*p)) for p in product(*params)]
    return do_sorted(results, key=lambda (params, result): key(result))

**Comment by amueller** [comment]
Thanks. I think I have to look into dask in more detail before I can give any helpful feedback.
A very naive question: when / how will results be re-used?
in the cross-validation example that @mrocklin posted, in the middle there seems to be a lot of sharing going on. Is that just everybody accessing the ``score_params`` list?

I have an unrelated question that I forgot to ask on the weekend: what do you use for generating the graphs? There is an incompatibility between pydot and pyparsing in the current version of pydot IIRC, and pydot relies on graphviz, which is hard to install (and not available in anaconda for all platforms).

**Comment by mrocklin** [comment]
We use graphviz to generate plots.  If the user doesn't have it we raise an informative error pointing them to where they can get it.

We use the Python `graphviz` library, mostly because it's python2/3 compatible.

**Comment by mrocklin** [comment]
Shared intermediates are held until all tasks that depend on them are finished.  Then they are are released.

**Comment by amueller** [comment]
A cool example would be using
```python
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import make_pipeline

iris = load_iris()
param_grid = {'linearsvc__C': np.logspace(-3, 3)}
grid = GridSearchCV(make_pipeline(StandardScaler(), LinearSVC()), param_grid=param_grid)
grid.fit(iris.data, iris.target)
```

I guess using the imperative interface we would need to rewrite the loops entirely.
That actually seems pretty tricky, and maybe we should just use caching? hum....

**Comment by ogrisel** [comment]
Related to this discussion: here are some experiments I did with dask for out-of-core, parallel cross-validation with dask on scikit-learn models that support `partial_fit`:

https://gist.github.com/ogrisel/ef8cbc1e42cef66d4184

I did experiments both with dask array and dataframe to handle the data and using the dict API of dask for the CV logic itself. Using the new imperative API might render this code more readable for people new to dask.

**Comment by cowlicks** [comment]
Here is my WIP attempt at analog of `make_pipeline`:
https://github.com/cowlicks/scikit-learn/blob/dask/sklearn/pipeline.py#L575-L593

Basically I wrapped each "transform" with `dask.imperative.value` I'm not sure this is working yet. I should check the unittests for pipeline.

And I'm working on a `DaskSearchCV` here:
https://github.com/cowlicks/scikit-learn/blob/dask/sklearn/grid_search.py#L954-L1041

All that I have done in the girdsearch part is remove joblib.

I'm testing this with the iris data like @amueller reccomended:
```python
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.grid_search import DaskSearchCV
from sklearn.pipeline import make_pipeline, make_dask_pipeline

from ipdb import set_trace
set_trace()
iris = load_iris()
param_grid = {'linearsvc__C': np.logspace(-3, 3)}

dpipe = make_dask_pipeline(StandardScaler(), LinearSVC())
dgrid = DaskSearchCV(dpipe, param_grid=param_grid)
r = dgrid.fit(iris.data, iris.target)
```

**Comment by cowlicks** [comment]
Hey @amueller what is the proper way for comaparing the equality of two estimators?

p.s. can I shoot you random questions over email?

**Comment by amueller** [comment]
You can, but I'm sick at the moment and slow to respond :-/
testing two estimators for equality after ``fit`` was called is hard. Before ``fit`` was called by comparing ``get_params``.
Why / when do you need that?

**Comment by amueller** [comment]
I'll probably not be able to review your attempt this week, I'll try on Monday or Tuesday. I'm not leaving my bed for now.

**Comment by cowlicks** [comment]
@amueller no worries, get well soon. 

I was trying to compare the result of my `DaskGridSearch` vs `GridSearchCV`. Currently I'm calling `.fit_transform(iris.data)` and comparing the arrays.

**Comment by amueller** [comment]
Ah. you want to see if the learned model is the same. ``decision_function(iris.data)`` is a good proxy for that.

for benchmarking ``iris`` is too small and also for ``StandardScaler`` there is probably not a huge gain. But it is a good / quick example for debugging.

If you want to benchmark, replacing ``iris`` by ``digits`` or ``load_mldata("MNIST")`` might be interesting, and replacing ``StandardScaler`` by ``RBFSampler``.

**Comment by mrocklin** [comment]
I'm surprised at how simple the changes to `Pipeline` were.  I suspect that the same simple changes to grid search aren't enough to get things to work.  There are cases where the control code depends on the value, e.g. there is a for loop over `range(len(value(out)))`, we might need to keep the original concrete `out` variable around for cases like this.

**Comment by amueller** [comment]
I don't think that much can be gained by using dask on anything after "out" is computed.
If out is just the result of the dask computation, I think that should be fine as a first go.

**Comment by mrocklin** [comment]
OK, I took a crack at this myself.  General feedback is that I found it fairly comfortable to wrap the scikit learn logic with dask imperative.  However, I ran into issues because of the reliance of the API on side effects.  For example I really want to have some token at the end of calling 

    result = estimator.fit(...)

but sadly it's quite idiomatic to just say the following:

    estimator.fit(...)

I'm not yet sure how best to get around this problem.  dask.imperative works much better when we can hand around tokens that represent tasks/graphs-of-tasks that need to be done.

**Comment by amueller** [comment]
Hm... I don't have a good answer to that... The API wasn't really designed with lazy evaluation in mind...

**Comment by mrocklin** [comment]
Yeah, this probably just means that if we want to make dask-enabled pipeline and gridsearch stuff then it probably can't be cleanly integrated into the existing code.  We'll probably have to make something new that has a different internal interface.

**Comment by ogrisel** [comment]
+1 for not sticking too strictly to the sklearn's API when it does not make sense from a dask point of view.

**Comment by mrocklin** [comment]
Closing this in favor of https://github.com/mrocklin/dasklearn and http://blaze.pydata.org/blog/2015/10/19/dask-learn/
