### ISSUE TITLE
array-overview.rst needs to be edited

### ISSUE THREAD

**Issue by NoonienSoong** [blaze/dask#598]
The last line of the .rst file needs to be changed since the np.full_like funtionality has been implemented in the array.wrap.py

**Comment by mrocklin** [comment]
Good point.  Can i interest you in submitting a pull request with a fix?

**Comment by NoonienSoong** [comment]
I would love to. However need write permission.

**Comment by mrocklin** [comment]
You can fork this repository, push the fix to your own fork, then submit a pull request asking us to merge those changes.

**Comment by NoonienSoong** [comment]
Done

**Comment by cowlicks** [comment]
Thanks @NoonienSoong closing.
