### ISSUE TITLE
Add Base.to_graphviz

### ISSUE THREAD

**Issue by sinhrks** [blaze/dask#611]
Add function to return ``graphviz`` instance created from dask graph for below reasons:

- When using IPython, ``.visualize`` outputs unnecessary image file
- Sometimes we want to modify graphviz instance directly

**Comment by jcrist** [comment]
I'm not too keen on having this as a method on collections, seems a little extraneous. `dask.dot.to_graphviz` could be changed to accept either a dask graph or an instance of `Base`. Then this would work:
```python
>>> from dask.dot import to_graphviz
>>> g = to_graphviz(some_dask_collection)
```

Perhaps temporary files could be used by `visualize` when no path name is specified. This would still allow displaying through IPython notebook, but wouldn't clutter your directory with `mydask.*` files.

**Comment by sinhrks** [comment]
Thanks. On current master, specifying ``filename=None`` results in ``TypeError``.

```
d.visualize(filename=None)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I think this can be fixed to:

1. Return image using temporary file
2. Return image itself without saving a file
3. Return graphiz instance

Maybe option 2 is prefereable? (I want 3 in future, but it should be done via different option...)

**Comment by mrocklin** [comment]
Historically we've defaulted to a default filename, `'mydask'`.

**Comment by sinhrks** [comment]
Ah, I mean optionally accept ``filename=None`` without changing the default. Prepared a PR.
