### ISSUE TITLE
Add dask._merge to toplevel 

### ISSUE THREAD

**Issue by sinhrks** [blaze/dask#612]
There are lots of codes like: ```toolz.merge(dask, [x.dask for x in seq])```.

How about adding ``_merge`` function which can handle ``dict``, ``Base`` and nested list for internal use? It accepts `_merge(dask, seq)`.

```
def _merge(*dasks, **kwargs):
    """ Merge a collection of dask instances and dicts """
    
    result = dict()
    for dask in dasks:
        
        if isinstance(dask, Base):
            dask = dask.dask
        elif isinstance(dask, list):
            # for nested list
            dask = merge(*dask)

        result.update(dask)
    return result
```

**Comment by mrocklin** [comment]
I personally like using the explicit `toolz.merge` function.  My preference is to use general purpose functions as much as possible, even if they are slightly inconvenient.

**Comment by sinhrks** [comment]
I've looked through and found there are fewer cases than I initially thought. Let me close this.
