### ISSUE TITLE
Series vs. DataFrame confusion

### ISSUE THREAD

**Issue by lakshmanok** [blaze/dask#620]
I'm applying a function that returns a scalar to a group (alldata is a Dask dataframe):

```
def func(gp):
     return gp['Ref'].iloc[0]

estimates = alldata.groupby('Id').apply(func)
estimates.columns = ['rowno', 'Expected']   # unlike Pandas, this doesn't change column names
estimates.to_csv('out.csv',  index=False, index_label=False)  # doesn't work because estimates is not a DataFrame.  Instead it seems to be a Series
```

I find that estimates is now a Series, and Series doesn't support writing out. How can I write out all the values in this Series to disk? There is no values() method. I tried to work around this by using head()
```
estimates = estimates.head(n=len(estimates))
pd.DataFrame({'Id': np.arange(1,len(estimates)+1), 'Expected': estimates}).to_csv(...)
```
but this doesn't work either because only the first partition is written out, not the full file.

**Comment by mrocklin** [comment]
Apply is, as in Pandas, always a little wonky.  

I suspect that you'll have a better time if you use `.apply(func, columns=...)` rather than trying to mutate the columns directly.

I've added `Series.to_csv` in https://github.com/blaze/dask/pull/621

**Comment by mrocklin** [comment]
Hrm I wonder if we should force the user to supply `columns=` in apply calls.  This would likely avoid a lot of surprises.

**Comment by lakshmanok** [comment]
First of all, thanks for your suggestion on using apply(func, columns) and for the prompt change. 

apply(func, columns) worked, and the resulting Series has the right column names.

When will Series.to_csv() get merged into master? The reason I ask is that I'm providing example code for a Kaggle contest, and don't want to make people figure out how to install specific branches of dask.

Until then, is there a work-around to Series.to_csv?  For example, is there a way to create an out-of-core DataFrame using the Series, and then call DataFrame.to_csv?  I tried to change 'func' to return a tuple instead of a scalar, but apply() still returns a Series.

**Comment by mrocklin** [comment]
I've just merged #621 

Creating a `DataFrame` from a `Series` seems like a useful operation as well.

**Comment by mrocklin** [comment]
See https://github.com/blaze/dask/pull/623

**Comment by mrocklin** [comment]
> I tried to change 'func' to return a tuple instead of a scalar, but apply() still returns a Series.

Note that, unlike with pandas, dask.dataframe is unable to run your function on some sample data to get a sense of what the output will be.  This means that we are far less intelligent than Pandas about guessing output types, hence the need to give the columns explicitly.
