### ISSUE TITLE
Add CPU, memory, and disk usage to Profiler

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#637]
I'm running a parallel application using `dask.do` on a 16 core machine.  When computing I find myself watching `top` on the side, looking for the following information

1.  How does CPU activity track over time?
2.  How does memory use track over time?
3.  How close does memory use get to full?  When do we start swapping to disk?
4.  What parts of my computation are engaging disk?

**Comment by mrocklin** [comment]
[`psutil`](https://pythonhosted.org/psutil/) can give some of this information.  I wasn't able to get CPU activity very well after a couple minutes of trying.  It's unclear how we would record and present this to the screen.  Recording is a bit tricky because we only call the callbacks between tasks, so presumably this would underestimate cpu activity.  One could consider a separate thread, although this might be more trouble than it's worth.  

A simpler and easier first pass would be to just add memory use.

**Comment by jcrist** [comment]
[psutil](https://github.com/giampaolo/psutil) would be a great way of measuring these things, especially since we can get process/thread specific usage. How important is this right now compared to other tasks? How important is this information in real0time?

**Comment by mrocklin** [comment]
I hadn't even thought of realtime.  That idea has been floating out there for a while.  We would probably want other stuff for real time computation as well.  Responding to priority question off list.

**Comment by jcrist** [comment]
What I would do if I did this fully:
- Tie in to the pool object to get a list of process/thread ids
- Spin up a second process to track resource usage across all ids, and push to a queue feeding profiler

**Comment by mrocklin** [comment]
Profiler currently works off of static data (which is nice sometimes.)  Presumably this would need interaction with a live bokeh server, yes?

**Comment by jcrist** [comment]
Not necessarily the bokeh server. I did some experiments with a subprocessed flask app that were promising. This would mean the user wouldn't have to start up anything extra, and would *just work* from the shell. We could also use something other than bokeh, but I like the bokeh plots for after the fact visualization, so I'd be reluctant to change.

**Comment by mrocklin** [comment]
Is a subprocessed flask app nicer than a subprocessed bokeh-server?  It'd be interesting to think about why the bokeh-server might feel heavy weight.

**Comment by jcrist** [comment]
I suppose the bokeh server could be started as a subprocess as well. I was just looking for a way that the user didn't have to start something up themselves.

**Comment by jcrist** [comment]
Closed by #687.
