### ISSUE TITLE
it would be nice to have it also in a wheel format on Pypi

### ISSUE THREAD

**Issue by stonebig** [blaze/dask#662]
a dask-0.7.1-py2.py3-none-any.whl

````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

**Comment by mrocklin** [comment]
Interestingly we're chatting about release process over at #660 .  Perhaps you can recommend an addition to that workflow on that issue?

**Comment by cowlicks** [comment]
@stonebig there is now a wheel available for the latest release -- 0.7.3.

**Comment by stonebig** [comment]
thanks !

**Comment by stonebig** [comment]
no more wheel for 0.7.6 ?

**Comment by mrocklin** [comment]
My apologies @stonebig is there a convenient way to add this?

**Comment by stonebig** [comment]
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

**Comment by mrocklin** [comment]
```
mrocklin@workstation:~/workspace/dask$ twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading dask-0.7.6-py2.py3-none-any.whl
Uploading dask-0.7.6-py3-none-any.whl
Uploading dask-0.2.1.tar.gz
HTTPError: 400 Client Error: A file named "dask-0.2.1.tar.gz" already exists for  dask-0.2.1. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
```

**Comment by stonebig** [comment]
maybe 
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/dask-0.7.6*
````

**Comment by mrocklin** [comment]
It worked regardless.  Just not sure why the extra ancient version is there.

**Comment by stonebig** [comment]
probably because you did first a `python setup.py sdist bdist_wheel ` , so the `py3` only has been generated once.

Problem is if you update your code, that 'old' wheel won't be recomputed, but send nevertheless to pypi

**Comment by ogrisel** [comment]
If you want to use `python setup.py sdist bdist_wheel` without forgetting about the `--universal` CLI argument you can add the following section to `setup.cfg`:

```
[wheel]
universal=1
```
