### ISSUE TITLE
Is there a hidden random seed in dask?

### ISSUE THREAD

**Issue by lakshmanok** [blaze/dask#665]
Running this twice on a dask dataframe returns different results in 'outfile' each time:

```
alldata = dd.read_csv(infile)
alldata = alldata.set_index('Id')
estimates = alldata.groupby(alldata.index).apply(myfunc, columns='Expected')
estimates.to_csv(outfile, header=True)
```

myfunc is deterministic.  Yet, if I run the script twice, I get different results.  The format of the input file is as follows:

```
Id,minutes_past,radardist_km,Ref,Ref_5x5_10th,Ref_5x5_50th,Ref_5x5_90th,RefComposite,RefComposite_5x5_10th,RefComposite_5
x5_50th,RefComposite_5x5_90th,RhoHV,RhoHV_5x5_10th,RhoHV_5x5_50th,RhoHV_5x5_90th,Zdr,Zdr_5x5_10th,Zdr_5x5_50th,Zdr_5x5_90
th,Kdp,Kdp_5x5_10th,Kdp_5x5_50th,Kdp_5x5_90th
1,1,8.0,,,,14.0,,,,15.0,,,,,,,,,,,,
1,5,8.0,10.0,,10.0,18.0,11.5,,11.0,18.0,,,,,,,,,,,,
2,0,15.0,,,,,,,,,,,,,,,,,,,,
2,4,15.0,,,,,,,,,,,,,,,,,,,,
2,8,15.0,,,,,,,,,,,,,,,,,,,,
2,12,15.0,,,,,,,,,,,,,,,,,,,,
3,3,11.0,22.5,15.0,25.5,34.5,29.5,15.0,27.5,36.5,0.885,0.86833334,0.95166665,0.9716667,0.5,-0.25,0.5625,2.375,1.4099884,-
5.3200073,0.34999084,3.869995
3,8,11.0,,,,22.0,,,,28.5,0.92833334,0.9316667,0.945,0.97833335,1.5625,-0.1875,0.875,1.625,-0.69999695,-5.6200104,-0.69999
695,2.119995
```
The file itself is 8 million lines long.

**Comment by mrocklin** [comment]
There isn't a random seed in this case, it's just multiple threads acting non-deterministically in the groupby's shuffle.

I suspect that the issue here is that we're not guaranteeing a fixed order within each group.  Perhaps we should sort groups before sending them to myfunc?

I'm curious, what is pandas' policy during a `groupby(...).apply(myfunc)`?  Do the dataframes sent to myfunc obey some canonical ordering?

**Comment by shoyer** [comment]
> I'm curious, what is pandas' policy during a groupby(...).apply(myfunc)? Do the dataframes sent to myfunc obey some canonical ordering?

Yes, I'm pretty sure pandas preserves the original order of elements in a groupby/apply. I'm not sure if that's actually guaranteed as part of the API though.

**Comment by mrocklin** [comment]
Preserving original order is going to be *hard*.  

The two options I see are sort or ignore.  Thoughts?

**Comment by shoyer** [comment]
Here's a timely reference for the pandas behavior: https://github.com/pydata/pandas/pull/10931/

**Comment by lakshmanok** [comment]
Thanks! I think not having the original order preserved is
counterintuitive. However, if the original dataframe has some natural
ordering, users can do a sort in myfunc, so it is not the end of the world.

Perhaps, just document this difference in the API?

**Comment by mrocklin** [comment]
See https://github.com/blaze/dask/pull/669

**Comment by lakshmanok** [comment]
I don't think that this is fixed.  I updated to the latest 'master', and even tried sorting the group within "myfunc".  Here's a short program that illustrates the problem:

```
#!/usr/bin/env python
import dask.dataframe as dd
import numpy.random as rnd
import pandas as pd
import numpy as np
import sys

# create test file to illustrate problem
infile="/tmp/sample.csv"
fp = open(infile, 'w')
fp.write("Id,Minute,Ref\n")
for i in xrange(1000,2000):
    for minute in xrange(0,rnd.randint(5,8)):
        fp.write("{0},{1},{2}\n".format(i, minute, rnd.randint(30,60)))
fp.close()

# define function to operate on group
def myfunc(hour):
    hour.sort('Minute', ascending=True)  # note that sort here doesn't help
    return hour['Ref'].iloc[0]

for iter in xrange(0,2):
   outfile="/tmp/sample_soln_{0}.csv".format(iter)
   # read file
   alldata = dd.read_csv(infile, chunkbytes=1000)
   alldata = alldata.set_index('Id')
   # compute and write CSV
   estimates = alldata.groupby(alldata.index).apply(myfunc, columns='Expected')
   estimates.to_csv(outfile, header=True)

print "Run:  diff /tmp/sample_soln_0.csv /tmp/sample_soln_1.csv"
```

**Comment by mrocklin** [comment]
Note that by default `DataFrame.sort` doesn't operate in place.  You might want the following.

```python
# old
hour.sort('Minute', ascending=True)  

# new
hour = hour.sort('Minute', ascending=True)  
```

By adding this I get the following:

```
mrocklin@workstation:~/tmp$ python 665.py 
Run:  diff /tmp/sample_soln_0.csv /tmp/sample_soln_1.csv
mrocklin@workstation:~/tmp$ diff /tmp/sample_soln_0.csv /tmp/sample_soln_1.csv
mrocklin@workstation:~/tmp$ 
```

**Comment by lakshmanok** [comment]
thanks, yes, changing to sort the group fixes the problem.
