### ISSUE TITLE
Controlling data storage with dask.array.image imread

### ISSUE THREAD

**Issue by 22csnyder** [blaze/dask#672]
This is a follow up to my previous well answered SO question:
http://stackoverflow.com/questions/31951507/out-of-core-4d-image-tif-storage-as-hdf5-python

There are two limitations not addressed. I will work on my own workaround in the meantime--maybe I can make a small poorly written contribution one day to this end.

1) image.imread currently assumes that the images should be stacked "one after the other". As an example, say I have T time points of 3D data of shape (X,Y,Z). If I had already 3D stacks of tiff images of the shape (X,Y,Z) I would be fine. However, the way the data is formatted is with T*Z images of shape (X,Y) images, as I currently have the data in files of 2D information. This is realistic in the case that (X,Y,Z) can not fit in memory. The current method fits the data into a dask array of shape (T*Z,X,Y).

2) Currently the data is chunked file-wise. This may not always be ideal. Chunking of a large array I think should reflect the type of slicing that is intended. It would be nice if the user could specify this somewhere. In my use case I am typically interested in a large 3D volume at a single time point (1,big,big,big), or a small area that is observed overtime (big,small,small,small). In the second case, chunking file-wise would be disastrous. It is my understanding that every chunk would have to be loaded iff every timepoint is analyzed. I think chunks of size (1,small,small,small) would be more sensible.

Sorry to be needy. Thanks for the awesome software. 

Chris Snyder

EDIT1:
Sorry I realize that problem 1 can be fixed with something like:

```python
dsk = dict(((name, i//Z, i%Z) + (0,) * len(sample.shape),
            (add_leading_dimension2, (sk_imread, filename)))
            for i, filename in enumerate(filenames))
chunks = ((1,) * T,) + ((1,) * Z,) + tuple((d,) for d in sample.shape)
```
It might be nice to have this option as part of imread. Problem 2 is still unclear to me.

**Comment by mrocklin** [comment]
Hi Chris, 

Thanks for the feedback.  I was also pretty happy with the result of the SO question.  Thanks for raising it and for following up.

1.  It would be pretty easy to turn a nested list of filenames into an appropriate dask.array.  E.g. if we can get the following list of lists

    ```python
    [['a.r.tiff', 'a.g.tiff', 'a.b.tiff'],
     ['b.r.tiff', 'b.g.tiff', 'b.b.tiff'],
     ['c.r.tiff', 'c.g.tiff', 'c.b.tiff'],
     ...]
    ```

    then it should be easy to make the array.  Is a list of lists like this an appropriate input to `imread`?  Can we expect users to be able to produce such a list?  It would be nice to support an API like the following

        da.image.imread('*.*.tiff')
  
    and have the different stars interpreted as different dimensions.  We would still need code to produce the list of lists from the double-glob string.  Do you have any thoughts on how to do this?

2.  Regarding region-wise slicing do image formats (and image reading libraries) support partial reads?  Is there a function we can use to pull out only certain columns and rows from the underlying image?

**Comment by 22csnyder** [comment]
Dr. Rocklin, (and Dan -- see point 2)

Thanks for the followup. I'll respond inline

1.It would be pretty easy to turn a nested list of filenames into an
appropriate dask.array. E.g. if we can get the following list of lists

[['a.r.tiff', 'a.g.tiff', 'a.b.tiff'],
 ['b.r.tiff', 'b.g.tiff', 'b.b.tiff'],
 ['c.r.tiff', 'c.g.tiff', 'c.b.tiff'],
 ...]

I like this idea, and I hadn't thought of it. I would propose instead just
specifying the "shape" to the imread function though. No matter if the list
of the user's files are formatted img_a.b.tiff or img_.c.tiff I think they
should be in the same order... probably? So, just passing the dims:
da.image.imread(file_list,dims=(d1,d2,...)) and asserting that
len(file_list)=d1*d2*d3.... That's how I would handle it. I feel reasonably
comfortable that I could write this later--perhaps within a week or so.

2. Regarding region-wise slicing do image formats (and image reading
libraries) support partial reads? Is there a function we can use to pull
out only certain columns and rows from the underlying image?

Regarding partial reads, Dan told me a few months ago that pims recently
added support for this, though I haven't had a chance/need to try it out.
That's the only software I've heard of that does it. I'll mention
numpy.memmap since that feels related but I don't know much about it.

Last thing: I was of the perhaps incorrect impression earlier that creating
a dask array stores the image as chunks in a hdf5 file. It looks instead
like dask merely stores the tiff_file and the function for loading that
file. It seems to work for me so far, but I'm confused: Wouldn't it be
faster to load each chunk if the data was read from an hdf5 file? (I fear
I'm betraying how little I understand)

Best,
Chris Snyder

**Comment by mrocklin** [comment]
The `dims=(...)` idea sounds good to me!

You're right that the current implementation of imread doesn't store the data anywhere, it's just telling dask.array where it can go to retrieve the data from image files when necessary.  The `imread` function should return instantly; it performs no actual work.  

However, as you point out, you might actually *want* to base your computations off of an HDF5 file for performance reasons.  This could be done in the following way:

```python
import dask.array as da
from dask.array.image import imread

im = imread('myfiles.*.tiff')  # wrap around existing images

dset = im.to_hdf5('myfile.hdf5', '/myimage')  # store to HDF5 file

im2 = da.from_hdf5(dset, chunks=im.chunks)  # wrap around HDF5 file
```

Saving will take time though and now you have two copies of your data rather than one.

**Comment by 22csnyder** [comment]
Cool! Thanks a lot. Bug me in like 2 weeks if I haven't gotten back to you
about extending imread.

Best,
Chris

**Comment by shoyer** [comment]
I'm not sure it's necessary to add support for dimensions in `da.imread`.

You can already do this currently with repeated calls to `imread` and `stack`:
```
da.stack([da.imread(files) for files in nested_files])
```

Alternatively, this could be a good use case for a dask array `reshape` method (see https://github.com/blaze/dask/issues/570 for some discussion).

You're absolutely right that you probably want more flexible chunking than than per file. I agree that HDF5 is a good storage mechanism, but there are a few things you should keep in mind before using dask's `to_hdf5` method:

1. `to_hdf5` stores the array on disk in the same chunks as the provided dask array. So you may need to `rechunk` your array first.
2. For more flexible data access and higher IO performance, you may not want to chunk your arrays on disk at all.

You currently can't skip chunking with dask's `to_hdf5`, but if you simply create an HDF5 dataset with h5py, the default does not use chunks. Note to @mrocklin -- the ability to customize chunks independently of dask.array would also be useful even if you do want to chunk the data, because it's often more performant to use dask.arrays with larger chunks than the chunks on disk.

**Comment by cowlicks** [comment]
Ping @22csnyder 

@shoyer would something like `da.to_hdf5(..., write_chunks=False)` work?

**Comment by shoyer** [comment]
I think Matthew actually added this feature in a recent PR... I'm pretty sure you can now say chunks=None to turn off chunking.

**Comment by shoyer** [comment]
PR #758 added support for `reshape`, which should solve your need for the `dims` argument. As long the image dimensions are along the last axes, this sort of reshaping will be very efficient.

**Comment by 22csnyder** [comment]
Hi Stephan,

Thanks for the heads up. I think I know what you mean. Let me sketch the
usual scenario, and you tell me if that would be covered efficiently by
this PR.

.. I load T*Z many 2d images each of shape (X,Y). I get a dask array which
is 3-dimensional of shape img.shape=(T*Z,X,Y). Let's say I'm interested in
the time information when x,y,z are all between 2 and 5.

img.reshape(T,Z,X,Y)
view = img(:,2:5,2:5,2:5).compute()

Best,
Chris Snyder

**Comment by shoyer** [comment]
@22csnyder Yes, that use case is very efficient:
```python
x = da.ones((20, 1000, 1000), chunks=(1, 1000, 1000))
x.reshape(4, 5, 1000, 1000)[:, 2:5, 2:5, 2:5].visualize()
```
![image](https://cloud.githubusercontent.com/assets/1217238/10149051/fc48dae8-65eb-11e5-9c73-4f45210d5094.png)

Notice that the graph consists of linear chains of tasks -- no complex mixing or forking.

**Comment by 22csnyder** [comment]
Excellent. Thank you very much.

Last question, once you slice, reshape and then call compute() you get a
numpy array back. Do you know if that array [always, usually, almost never]
contiguous? It's important because the way I use cython requires it. Of
course I could just call np.ascontiguousarray but I'm just curious.

Best,
Chris S

**Comment by shoyer** [comment]
It really depends on exactly what you're doing. I would certainly call ascontiguousarray either way -- the overhead would be minimal.

**Comment by mrocklin** [comment]
What's the status on this?  Can this be closed?

**Comment by 22csnyder** [comment]
Yes I think so. I'm more than happy populating dask with glob and tokenize
and then calling reshape.

Best,
Chris Snyder
