### ISSUE TITLE
Create docpage about how to use async scheduler

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#682]
There are various options and flags that are pretty handy in non-trivial use.  Currently the only documentation is more research-y.  It would be good to have a doc page that was about “How to run the thing you just made” (feedback from @seibert)

**Comment by seibert** [comment]
To add some more information here: The main thing that was lacking was some page that showed some simple examples of how to execute the dask graph that was created with different schedulers and different options to those schedulers.
