### ISSUE TITLE
Tool to diagnose the parallelizability of a dask graph

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#689]
I have a nice computational graph with lots of mostly-numeric functions.  However I'm only getting 200-300% CPU usage on a twelve core machine.  I'd like to track down which of my functions parallelize well and which don't.  I'd also like to test the purity of these functions, ensuring that they produce the same results on each execution.  What I need is a set of valid inputs for each of these functions and then to test them in some sort of testbed.  Fortunately the dask graph gives us exactly this set of inputs.  

I propose a sequential pass through the task graph where, at every task, we redundantly execute the function both sequentially and in parallel with a thread pool.  We record the speedup and verify purity.  We then pass along the arguments for the next task.

This would be a diagnostic on a graph.  The output would be a report on which functions parallelize well and are pure and which functions need work.

This may interest @eriknw and @jcrist

**Comment by mrocklin** [comment]
Hrm, this could probably just be done with the synchronous scheduler and a callback.

**Comment by shoyer** [comment]
I'm surprised you need to verify which functions are pure. That part is usually pretty obvious (at least it should be!). I also doubt it can be diagnosed reliability, especially for functions with side effects like writing to disk.

I agree that it would be useful to diagnose the parallelizability of tasks. The diagnostic might also try running tasks in a process pool for the sake of comparison, which could couple well with #457.

**Comment by mrocklin** [comment]
>  I'm surprised you need to verify which functions are pure. 

I'm working with a large-ish foreign codebase.  It's much easier wrap things with `do` than to investigate each function.

**Comment by mrocklin** [comment]
I'm currently getting by with just a decorator

```python
from time import time
from multiprocessing.pool import ThreadPool

nthreads = 4
njobs = 12
pool = ThreadPool(nthreads)

def benchmarkme(func):
    def bench_func(*args, **kwargs):
        seq_start = time()
        result = func(*args, **kwargs)
        seq_end = time()

        if seq_end - seq_start < 0.1:
            return result

        def g(_):
            return func(*args, **kwargs)

        par_start = time() 
        results = pool.map(g, [0] * njobs) 
        par_end = time() 

        ratio = njobs * (seq_end - seq_start) / (par_end - par_start)
        pure = all(str(result) == str(r) for r in results)

        print("Func: %s  Ratio: %f  Pure:  %s  Time: %f" %
                (func.__name__, ratio, pure, seq_end - seq_start))

        return result
    return bench_func
```

**Comment by mrocklin** [comment]
Closing as speculative
