### ISSUE TITLE
read_csv: passing index_col results in KeyError

### ISSUE THREAD

**Issue by willfurnass** [blaze/dask#714]
Sample data:
```
"id1","id2","attr1","attr2","attr3","attr4"
1072.0,"2014-02-22 12:30:00",1,93440248,"False",750
1072.0,"2014-02-22 12:45:00",1,93440248,"False",765
1072.0,"2014-02-22 13:00:00",1,93440248,"False",780
1072.0,"2014-02-22 13:15:00",1,93440248,"False",795
```

The following results in a `KeyError` (full stack trace on [pastebin.com](http://pastebin.com/nx1zBQA7)):
```python
dask_df = dd.read_csv('test.csv',  index_col='id1')
```

However, setting the index column using the `set_index` method works (e.g. as follows) for single-columned indexes ([MultiIndexes](http://pandas.pydata.org/pandas-docs/stable/advanced.html) are not yet supported in Dask).

```python
dask_df = dd.read_csv('test.csv')
dask_df = dask_df.set_index('id1')
```

Issue detected when using Dask 0.7.1 and pandas 0.16.2.

**Comment by mrocklin** [comment]
Indexes have to be a bit more strange when working in parallel.  I think that, for the moment we should just raise an informative error pointing people to use `set_index` explicitly.
