### ISSUE TITLE
random states may have same seed

### ISSUE THREAD

**Issue by clarkfitzg** [blaze/dask#719]
The current implementation of seeding the random number generator is:

```
seeds = [self._numpy_state.randint(np.iinfo(np.int32).max) for i in sizes]
```

This can result in repetition of seeds => random sequences are the same, which is probably not what users intend. The reasoning is the same as the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem) in probability.

```
from __future__ import division

import numpy as np
from scipy.misc import comb, factorial


def prob_same(k, n=np.iinfo(np.int32).max):
    '''
    Compute the probability that at least two seeds are the same
    '''
    different = comb(n, k, exact=True) * factorial(k, exact=True)
    total = n ** k
    prob_all_different = different / total
    return 1 - prob_all_different
```

Here's a few figures:
```
In [246]: prob_same(1000)
Out[246]: 0.00023257080042193845

In [247]: prob_same(10000)
Out[247]: 0.023011865852016755

In [248]: prob_same(50000)
Out[248]: 0.4412591367423576
```

So if there are 50000 chunks, there's a 44% chance that a seed will be repeated. Probably no big deal for most use cases, but it would be better to not have to make this assumption.

It's possible to eliminate this by just sampling with replacement. Ie. change the implementation to something like:
```
seeds = self._numpy_state.choice(np.iinfo(np.int32).max, size=len(sizes), replace=True)
```

I don't know if this alternative implementation would be totally valid, since it seems like more may be required. See this [paper by L'Ecuyer](http://www.iro.umontreal.ca/~lecuyer/myftp/papers/wsc15rng.pdf). But it would effectively guarantee different seeds.

**Comment by clarkfitzg** [comment]
cc @shoyer

**Comment by mrocklin** [comment]
Changing the replacement choice seems like a cheap and useful change to me.

**Comment by shoyer** [comment]
@clarkfitzg do you mean "eliminate this by sampling *without* replacement"? If you same *with* replacement, I think you'll still get this same problem.

**Comment by clarkfitzg** [comment]
@shoyer good catch. Yes, should be _without_ replacement.

**Comment by clarkfitzg** [comment]
So code should be
```
seeds = self._numpy_state.choice(np.iinfo(np.int32).max, size=len(sizes), replace=False)
```

I'll send a PR.

**Comment by mrocklin** [comment]
We do this trick in a few places if you feel adventurous :)

```
array/random.py
dataframe/core.py (twice)
dataframe/demo.py
```

**Comment by clarkfitzg** [comment]
Looks like Numpy tries to actually build the array here. This blows up the memory:
```
np.random.choice(2**31, size=10, replace=False)
```
So we'll need a helper function that can efficiently sample without replacement. This shouldn't be hard, but I'll have to come back to this.

**Comment by mrocklin** [comment]
```python
In [1]: def f(n):
   ...:     s = set()
   ...:     while len(s) < n:
   ...:         s.add(np.random.randint(2**31))
   ...:     return s

In [3]: import numpy as np

In [4]: f(5)
Out[4]: {100965301, 291247349, 453074527, 1324568001, 1941343223}
```

One shouldn't be afraid of pure python in cases like this.

**Comment by mrocklin** [comment]
Given that we do this a few times whatever solution we come to should probably live as a general utility function.

**Comment by clarkfitzg** [comment]
Yes, that's what I figured, and it's also why I hesitated on submitting a PR. Thanks for the reminder! I have a couple hours now, let me take another look.

**Comment by clarkfitzg** [comment]
An observation- `dataframe.DataFrame.random_split` takes `seed` as a parameter while `dataframe.DataFrame.sample` takes `random_state`. It would be nice if these were the same.
