### ISSUE TITLE
dask.dataframe is missing reindex and reset_index methods

### ISSUE THREAD

**Issue by thrasibule** [blaze/dask#734]
Right now the only way to update an index is to reload a dataframe from file, or is there a better way to do it?

**Comment by mrocklin** [comment]
Does `set_index` satisfy your needs?

The reindex method is probably doable as long as we don't care too much about order.  Can you describe what you're trying to accomplish?

**Comment by thrasibule** [comment]
Yes set_index(drop=False) works, that way I can always create a new index, but otherwise it seems to me once that setting the index in a dask dataframe is a non reversible operation. The only way to reset it is by reloading the dataframe from disk. I'll close this particular issue, since #735 probably gives a more concrete example of why being able to reset the index is needed.
