### ISSUE TITLE
Tokenize/hash numpy/pandas inputs

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#738]
Currently we tokenize numpy arrays with `(id(x), x.shape, x.dtype, x.strides)`

We should consider tokenizing based off of the data instead of the object id

    sha1(x.data).hexdigest()

This gets about 400MB/s on my old laptop.  We can also learn from what `joblib` does here.

This gets trickier on object dtype.  In this case we might want to depend on Python's hash + `.tolist`

    hash(x.flat.tolist())

This is slower but still not terrible.  We could also try `sha1('_'.join(...)).hexdigest()` in the event that all objects are strings.

**Comment by mrocklin** [comment]
Gitter conversation on this here https://gitter.im/BIDS/ds4ds?at=55fda8c218e0111d7e4fae35

**Comment by jcrist** [comment]
Was this 100% fixed in #742?
