### ISSUE TITLE
Special case apply in pprint_task

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#741]
When looking at profile plots, tasks that use apply become illegible

    f(x, y, z=10) # want to specify this
    (f, x, y, ??) # no way to specify kwargs
    (apply, f, (x, y), {'z': 10})  # so we use apply!
    (apply, f, (tuple, [x, y]), (dict, (list, [(list, ['x'])]), (list, [(list, [10])])])))  # but we also quote 

:(

We might consider special casing `apply` in the `pprint_task` function.  We might also consider a general `unquote` operation that would unpack all of the dict/list junk.  

cc @jcrist

**Comment by jcrist** [comment]
Unquote:

```python
def unquote(expr):
    if istask(expr):
        if expr[0] in (tuple, list, set):
            return expr[0](map(unquote, expr[1]))
        elif expr[0] == dict and expr[1][0] == list:
            return dict(map(unquote, expr[1][1]))
    return expr
```

`pprint_task` will probably have to use something different, to properly handle printing keys and things. Not sure.

**Comment by mrocklin** [comment]
Perhaps `pprint_task` just includes recursive cases for `(list, ...)` and `(dict, ...)`.

**Comment by jcrist** [comment]
For tasks with `apply`, would you want them to show `apply`? Or convert to normal call syntax, and show the dict as kwargs? I can see the merit in both options, just need a decision.

**Comment by mrocklin** [comment]
I suspect that most users are unfamiliar with `apply`.  I would opt to show them `f(x, y, z=10)` instead if possible.
