### ISSUE TITLE
DOC: Readthedocs doesn't work automatically?

### ISSUE THREAD

**Issue by sinhrks** [blaze/dask#770]
Latest build looks 2 weeks ago, and doc for v0.7.2 is not built.

https://readthedocs.org/projects/dask/builds/

**Comment by mrocklin** [comment]
I've triggered a build manually.  I'm not sure why it's not building on every push.  After a brief look at the settings I don't see anyplace to ask readthedocs to build automatically.

**Comment by shoyer** [comment]
@mrocklin you should see ReadTheDocs listed under Services on this page: https://github.com/blaze/dask/settings/hooks

**Comment by mrocklin** [comment]
Indeed.  I do.  Everything seems to be fine there.

**Comment by sinhrks** [comment]
Thanks, ``DataFrame`` API looks not rendered properly. Maybe caused by #733, but not sure as it works on local. 

http://dask.pydata.org/en/stable/dataframe-api.html

**Comment by mrocklin** [comment]
Perhaps your local sphinx version differs from the sphinx version used on readthedocs?

@sinhrks do you have an account on readthedocs?  I would be happy to give you access to the dask projects there if so.

**Comment by sinhrks** [comment]
Thanks, my account is "sinhrks".

About build problem, I'll check it using my own repo.
