### ISSUE TITLE
Core function to update dependencies, dependents

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#781]
Given an existing dask graph, and its derivative `dependencies` and `dependents` dicts.

```python
In [1]: from operator import add
In [2]: dsk = {'x': 1, 'y': (add, 'x', 10), 'z': (add, 'y', 'x')}

In [3]: from dask.core import get_deps
In [4]: dependencies, dependents = get_deps(dsk)

In [5]: dependencies
Out[5]: {'x': set(), 'y': {'x'}, 'z': {'x', 'y'}}

In [6]: dependents
Out[6]: {'x': {'y', 'z'}, 'y': {'z'}, 'z': set()}
```

And given a new graph that builds on top of the old one

```python
In [7]: new = {'a': (add, 'y', 10), 'b': (add, 'a', 20)}
```

Update dependencies and dependents efficiently in place.  This operation must be able to run well under both the large update case (new is large) and the many-frequent small update case (new is just a single added task).

A naive (and slow) solution would be to update dsk and then call `get_deps` again.

```python
In [8]: dsk.update(new)
In [9]: dependencies, dependents = get_deps(dsk)

In [10]: dependencies
Out[10]: {'a': {'y'}, 'b': {'a'}, 'x': set(), 'y': {'x'}, 'z': {'x', 'y'}}

In [11]: dependents
Out[11]: {'a': {'b'}, 'b': set(), 'x': {'y', 'z'}, 'y': {'a', 'z'}, 'z': set()}
```

This might serve as a decent setup for testing.

I believe that this is fairly straightforward but could use an eye for detail as it's likely to be depended upon fairly aggressively.  This is the sort of thing that might interest @eriknw if he has the time and inclination.

**Comment by eriknw** [comment]
I can get to this today.

What if the new graph shares keys with the old graph?  Should we override?

Also, what if the old graph has literals that are keys in the new graph?  Should they remain as literals?

I don't know what you plan to do with this, but I bet I'll like it!

**Comment by mrocklin** [comment]
We can assume that the new graph does not conflict with the old graph, e.g. all overlapping keys have identical values.

Overlapping literals is an interesting question.  I think that the right thing to do here is to follow the semantics of `get_deps(merge(old_dask, new_dask))` and so treat overlapping new literals as keys in the old graph.

**Comment by mrocklin** [comment]
Slight disclaimer, I'm still working through exactly how this fits into current work.  Needs are not fully formed.  It's possible that I might come back with a slight alteration so it might be best to delay this slightly.  I can work with the slow/naive solution for a while if necessary.

**Comment by eriknw** [comment]
Okay, no problem.

Is the original graph complete--that is, should we assume it can run and give correct results up to that point--or is the original graph a work in progress that may (for some reason) reference keys that have not been added yet?

**Comment by mrocklin** [comment]
It's complete.  The intent here is to support glomming on additional computations on the fly.  This is to support concurrent construction and execution of the graph.

**Comment by mrocklin** [comment]
Ah, sorry, but yes, at every stage the graph represents a consistent computation.

**Comment by mrocklin** [comment]
Ah, I think I see where you were going with this.  As I currently do things keys from the old graph that are attached to the new graph are wrapped in an object.  In my case this is a `RemoteData` object.  I currently unpack these in an explicit step.  This might need to be merged with the update process though.

Relevant functions on the `distributed.dask` side include [`RemoteData`](https://github.com/mrocklin/distributed/blob/master/distributed/client.py#L121), [`unpack_remotedata`](https://github.com/mrocklin/distributed/blob/master/distributed/client.py#L334), and [`insert_remote_deps`](https://github.com/mrocklin/distributed/blob/master/distributed/dask.py#L178).  It's not clear though how this sort of wrapping behavior would best be integrated into decisions made in core dask though, if at all.

**Comment by eriknw** [comment]
Thanks for the context.  I think I understand, and will look more closely at the linked `distributed.dask` elements once I dive into this.

To keep things efficient and to introduce the least amount of complexity, I think we should assume that there are no *literals* in the old graph that overlap with the *keys* in the new graph.  If we want to assert this efficiently, we would need to keep track of hashable literals.

**Comment by mrocklin** [comment]
I believe that to be a fair assumption.

I apologize also for this problem not being as clear cut as I originally thought.  I'd be happy for this to stall for a while until I can produce a clearer problem statement.

**Comment by eriknw** [comment]
Okay, although I think the goals and assumptions are pretty clear now.  Perhaps I'll update `cytoolz` first, then do this.

**Comment by mrocklin** [comment]
I may have to do something more custom than this in `distributed`.  Closing for now; may reopen in a day or two.
