### ISSUE TITLE
dataframe column names getting scrambled

### ISSUE THREAD

**Issue by rabernat** [blaze/dask#787]
I am loading from data from bcolz into a dask dataframe. After applying a ``.where()`` operation, the column names get scrambled.

Unfortunately I haven't been able to reproduce this with a simpler example. But here it is. Quite stuck and frustrated. (Dask version 0.7.3.)

```python
from dask import dataframe as dd
bdf = dd.from_bcolz(fname)
bdf.loc[0].compute()
```
gives
```
npart    3073441.000000
time           0.000000
vort           0.000001
x            225.023438
y            -19.984375
Name: 0, dtype: float32
```
but if I do
```
bdf.where(bdf.time==0).loc[0].compute()
```
I get
```
npart    3073441.000000
time           0.000000
x              0.000001
y            225.023438
vort         -19.984375
Name: 0, dtype: float32
```

The ``x`` and ``vort`` columns have been exchanged.

Any idea what is wrong and how to fix it?

**Comment by mrocklin** [comment]
Hrm, odd.  Do you have a small example that you can share that I can take a
look at?

What happens if you use dd.from_array?

bc = bcolz.ctable(rootdir='...')
df = dd.from_array(bc)

**Comment by rabernat** [comment]
I am struggling to create a small example (will try), but in the meantime, I can confirm that your version with ``dd.from_array`` does NOT produce the same problem. (Also pure pandas does not make produce the problem.)

**Comment by mrocklin** [comment]
The `from_bcolz` function will be a more efficient because it'll leverage
the column-store nature of bcolz.

I find myself tempted to remove it though, just to reduce the maintenance
burden of dask.dataframe.  I'm not surprised to find a bug here.  This
particular codepath is infrequently used.

However, from_bcolz gets used then we should definitely continue to support
it.  E-mail responses like this help to motivate this work.

**Comment by rabernat** [comment]
As you might be able to infer from the issues I have been leaving around, I am trying to build a pipeline for storing and processing a ton of binary data. I read your [post on castra](http://matthewrocklin.com/blog/work/2015/08/28/Storage/) and that sounded like a perfect solution for my problem. Unfortunately I couldn't easily get castra working (see anaconda-issues/issues#456), so I decided to fall back on bcolz, which seems to share some of the advantages.

At this point, I have a bunch of data in bcolz format. So I would be happy if dask would continue to support it directly. But I realize these tools are quite new and still in flux.

**Comment by mrocklin** [comment]
OK.  I'll take a look at this issue tomorrow.  It's probably just something
silly.

**Comment by mrocklin** [comment]
See fix in https://github.com/blaze/dask/pull/792
