### ISSUE TITLE
Dask Bag global imports

### ISSUE THREAD

**Issue by eribean** [blaze/dask#804]
Using Bag to create chunks of random array's results in named error on numpy.  Imports should be serialized in bag.

The following doesn't work
```python
from dask.bag import from_sequence
import numpy as np

if __name__ == "__main__":
    def create_array(x):
        return np.random.rand(x, 10)
    
    bag = from_sequence([4, 4, 4, 4, 4, 4, 4, 4], 4)
    data = bag.map(create_array).compute()
```
the error is:
> dask.async.NameError: global name 'np' is not defined

The following, however, does work
```python
from dask.bag import from_sequence

if __name__ == "__main__":
    def create_array(x):
        import numpy as np
        return np.random.rand(x, 10)
    
    bag = from_sequence([4, 4, 4, 4, 4, 4, 4, 4], 4)
    data = bag.map(create_array).compute()
```

**Comment by mrocklin** [comment]
Ping @mmckerns is there a way to make dill manage these cases?

**Comment by cowlicks** [comment]
This works for me with dill 0.2.4 python 3.4

**Comment by eribean** [comment]
I am running dill 0.2.4 with Python 2.7.6.  Still seeing errors....

**Comment by mmckerns** [comment]
If I'm not mistaken, this has nothing to do with `dask` -- and is basically asking for `dill` to support pickling a module that is referred to in the local scope, but imported in the global scope.  In at least the development version of `dill` this is supported -- on windows (using a forked pickle) or linux, in `2.x` and `3.x`, and with `dill.settings['recurse'] = x` where `x = True` or `x=False`.  However, I believe this has been supported in more recent versions of `dill`.  @eribean: can you give me some details on your platform (e.g. Windows, mac, ...)?  If you are still seeing errors, can you check if you are seeing the error without `dask` (i.e. just with `create_array`)?  Can you also try with 'recurse` set to `True`?

I'm using `dill` version `0.2.5.dev0` and `python` version `2.7.10`

**Comment by eribean** [comment]
@mmckerns:  The following worked:
```python
from dask.bag import from_sequence
import numpy as np
import dill
dill.settings['recurse'] = True

if __name__ == "__main__":
    def create_array(x):
        return np.random.rand(x, 10)
    
    bag = from_sequence([4, 4, 4, 4, 4, 4, 4, 4], 4)
    data = bag.map(create_array).compute()
```

I agree this isn't an issue with Dask, and it probably isn't an issue with dill either.  Is there a global settings file so that I can set it once and never worry about it again?

**Comment by mmckerns** [comment]
@eribean: in `dill`, no -- there is the `settings` dict, which you can set once for each instance of python.  The behavior you are looking for will very likely become the default in the near future, but currently it isn't.

**Comment by mrocklin** [comment]
@mmckerns do you have a rough timeline on when this will become default behavior.  No pressure here (we're all busy), just trying to plan things.

**Comment by eribean** [comment]
Should I close the issue?

**Comment by mrocklin** [comment]
I think that this is a valid usability issue for dask, even if it originates from another library.  We need to find a solution for it one way or another.  Lets keep it open for now.

**Comment by mrocklin** [comment]
We've moved dask to cloudpickle until the global issues in dill get resolved.  Closing this for now.

**Comment by mmckerns** [comment]
@mrocklin: somehow didn't see your question from Oct 31.  The answer is when the move to this setting doesn't lose functionality.  Right now, the change both adds and loses a little bit of functionality.  No timeline yet.  Maybe a smart choice is to allow the user to set the serializer?  This is what `IPython`, `mpi4py`, and others have done when presented with the choice of `dill` vs `cloudpickle`.
