### ISSUE TITLE
EOFError when using dask.multiprocessing in dask tutorial example 02-Foundations

### ISSUE THREAD

**Issue by alancj** [blaze/dask#809]
I was running through the dask tutorial, and couldn't figure out why this step in particular didn't work for me whilst the rest worked (e.g. dask.threading worked fine). Is this expected behaviour when running on a windows machine?

from dask.multiprocessing import get
get(dsk, 'z')  # Execute in multiple processes
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-8-bec152849e0d> in <module>()
      1 from dask.multiprocessing import get
----> 2 get(dsk, 'z')  # Execute in multiple processes

C:\Anaconda\lib\site-packages\dask\multiprocessing.pyc in get(dsk, keys, optimizations, num_workers, func_loads, func_dumps, **kwargs)
     41         cleanup = False
     42 
---> 43     manager = multiprocessing.Manager()
     44     queue = manager.Queue()
     45 

C:\Anaconda\lib\multiprocessing\__init__.pyc in Manager()
     97     from multiprocessing.managers import SyncManager
     98     m = SyncManager()
---> 99     m.start()
    100     return m
    101 

C:\Anaconda\lib\multiprocessing\managers.pyc in start(self, initializer, initargs)
    526         # get address of server
    527         writer.close()
--> 528         self._address = reader.recv()
    529         reader.close()
    530 

EOFError:

**Comment by mrocklin** [comment]
That looks quite odd.  It's not failing in dask code, it's failing to produce a `multiprocessing.Manager()`

Can you try to create such a manager outside the context of dask?

```python
import multiprocessing
multiprocessing.Manager()
```

Are you running this in a special context somehow or are you just running the Jupyter notebook?  Python multiprocessing and Windows can be finicky.

**Comment by mrocklin** [comment]
So far I'm unable to reproduce this on my Windows virtual machine.  I cloned the dask-tutorials repository, navigated to that directory using a git-bash shell, then typed `ipython notebook 02-Foundations.ipynb` and ran through all of the cells happily.

**Comment by cowlicks** [comment]
@alancj If you are in the dask source directory can you try running this from a separate directory? It might sound odd. There are subtle bugs caused by some combination of windows multiprocessing implementation, pickling, relative and absolute imports, and the fact that dask has module named multiprocessing (which collides with the multiprocessing module in the python stdlib.

**Comment by alancj** [comment]
@mrocklin I'm running this in a Jupyter notebook, and when I try multiprocessing.Manager() I get the same error as above. In addition, I also see this error in stdout:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__

@cowlicks I'm running this in just a directory where I cloned the repo into, and also tried multiprocessing.Manager() from different directories but still get the same error.

**Comment by mrocklin** [comment]
Hrm, I suggest trying to track down the source of the error with `multiprocessing.Manager()`, perhaps by trying other variants, like `multiprocessing.Pool()` or by trying this in different environments, like a python script.

The fact that the standard library `multiprocessing` isn't functioning signals that there is something wrong the environment that it is possibly deeper than dask.

**Comment by alancj** [comment]
Yeah, definitely nothing to do with dask specifically so I'll close the ticket. I just ran through the steps of the tutorial in a python script and everything worked perfectly fine, no error with ```multiprocessing.Manager()```.

I think I'll try steer clear of windows + notebook + multiprocessing because it seems to be flaky at best from chatting to others who've had similar issues with that combination. 

Thanks for the pointers @mrocklin and @cowlicks! Looking forward to making good use of dask in my work :)
