### ISSUE TITLE
strange header handling by `read_csv()` 

### ISSUE THREAD

**Issue by DSLituiev** [blaze/dask#823]
I try to read my tab-delimited file and get a first line read as *both* column names and data:
```
rna = dd.read_csv( "rna.genes", sep = "\t")

rna.head()
Out[17]:
    gene_id             ind1            ind2            ind3  \
0   gene_id             ind1            ind2            ind3
1       7SK     3.36044620815043    4.64443203904666    4.07678875629324
2      A1BG  -0.0389951964702306  -0.154209400360407  -0.468014378675135
3  A1BG-AS1     1.65786753867809    1.41862348617062    1.05311387052091
4      AAAS     6.26481346044815    5.61889903381875    5.84721446019984
```

In addition when I call whether `loc` or `iloc` to double check what is the first line I get errors:

    rna.loc[0]
    ...
    ValueError: Can not use loc on DataFrame without known divisions

    rna.iloc[0]
    NotImplementedError: Dask Dataframe does not support iloc

I read [this tutorial](http://app.mybinder.org/2950383534/notebooks/dask-dataframe-basics.ipynb), but still did not get how to slice the dask tables.

**Comment by mrocklin** [comment]
The double header issue is indeed odd.  Can you provide a small sample that reproduces the problem?

Loc only works when the dataframe has known [partitions](http://dask.pydata.org/en/latest/dataframe.html#partitions).  Unfortunately CSV files don't give us this information naturally, so we don't know, for example, where in the file the millionth entry is.  If you just want the first few lines however you can always use `.head()`.

Your life might be better if you convert your csv files to hdf5 as in 

    dd.read_csv(...).to_hdf('filename.h5', '/data')

**Comment by DSLituiev** [comment]
I cannot attach files as I have no write permission to this repository.  Please save following to a `test.tab` and make sure the tabs stay tabs:

```
SNP	gene	beta	t-stat	p-value	FDR
chr22:24383284	GSTT1	0.41578429979963	12.4829821462724	1.51422020504144e-17	6.32523496271855e-12
chr22:24372116	GSTT2	0.421553200793657	12.4382517630312	1.74998788547579e-17	6.32523496271855e-12
chr22:24346258	GSTT3	0.512315241744027	10.2518229631821	2.81456935069628e-14	6.78207074451829e-09
```
If I follow your suggestion I get:

```
dd.read_csv("test.tab", sep = "\t").to_hdf("test.h5", "/data")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-910360b18a07> in <module>()
----> 1 dd.read_csv("test.tab", sep = "\t").to_hdf("test.h5", "/data")

//anaconda/lib/python3.4/site-packages/dask/dataframe/core.py in to_hdf(self, path_or_buf, key, mode, append, complevel, complib, fletcher32, **kwargs)
    505         from .io import to_hdf
    506         return to_hdf(self, path_or_buf, key, mode, append, complevel, complib,
--> 507                 fletcher32, **kwargs)
    508
    509     @derived_from(pd.DataFrame)

//anaconda/lib/python3.4/site-packages/dask/dataframe/io.py in to_hdf(df, path_or_buf, key, mode, append, complevel, complib, fletcher32, get, **kwargs)
    595                             'fletcher32': fletcher32}))
    596
--> 597     DataFrame._get(merge(df.dask, dsk), (name, i), get=get_sync, **kwargs)
    598
    599

UnboundLocalError: local variable 'i' referenced before assignment
```

In case:
```
from dask import __version__ as ver
ver
Out[3]: '0.7.5'
```

**Comment by mrocklin** [comment]
These issues are both fixed in https://github.com/blaze/dask/pull/824

The `to_hdf` failure was because we weren't handling the case where the dataframe was only a single partition (i.e. fairly small).

The repeated header failure was because our function to identify the presence of a header wasn't looking at all of the input keyword arguments and so was missing the `sep='\t'` bit.  Both are fixed in #824 , which should be merged shortly.

**Comment by mrocklin** [comment]
#824 has been merged.  @DSLituiev can you verify that this resolves your problems?

**Comment by DSLituiev** [comment]
I now did:

```
pip3 uninstall dask
git clone https://github.com/blaze/dask
cd dask
python3 setup.py develop
```

and I am getting the same behaviour with the header ;((

**Comment by DSLituiev** [comment]
is `infer_header` supposed to return True if there is a header? If so, I would rename it to `has_header`. What is that regex doing?

**Comment by mrocklin** [comment]
Yeah, I'm looking at that exact part of the code now myself.  Nice sleuthing.

**Comment by mrocklin** [comment]
Yeah, so this is a little tricky.  As you guessed we need to figure out if the CSV file actually has a header or not.  It's not trivial to determine this.  It looks like the current solution is looking for column names that look roughly like words, and that this chokes on your (perfectly reasonable) use of hyphens.  We could extend the regex, but this entire solution looks a little brittle to me.

Any suggestions?

**Comment by mrocklin** [comment]
I'm now just comparing `pd.read_csv(..., header='infer')` against `pd.read_csv(..., header=None)`, which seems like a sane solution to me.  I'm currently running into a problem that `pd.read_csv(..., header='infer')` seems to always infer that the file has a header.

**Comment by mrocklin** [comment]
OK, I think that this is resolved in https://github.com/blaze/dask/pull/827

**Comment by DSLituiev** [comment]
thank you. Resolved
