### ISSUE TITLE
non-unique names in da.from_array cause problems with da.stack

### ISSUE THREAD

**Issue by rabernat** [blaze/dask#829]
This is an obscure problem which I can't reproduce using a simple example. I thought I would open an issue anyway.

I have an experimental [module](https://github.com/xgcm/xgcm/blob/master/xgcm/mdsxray.py) that generates dask arrays from a binary file store and feeds them to xray with the proper metdata

It loops through a timeseries of files and does something roughly like this

```python
vardata = []
# build a list of dask arrays
for n in range(timesteps):
    data = function_to_load_binary_data(n)
    myda = da.from_array(data, data.shape)
    vardata.append(myda)
# stack them
vardask = da.stack(vardata)
```

The problem is that, evidently, the dask name attribute is not unique for the different arrays in the list, leading to problems with stack. If I do

```python
for n in range(len(vardata)):
    print 'vardata[%g] sum %g, name %s' % (n, 
        vardata[n].sum(), vardata[n].name)
    print 'vardask[%g] sum %g' % (n, 
        vardask[n].sum())
```
I get the following output
```
vardata[0] sum 22706.5, name from-array-a1d722948a08ee25f34c508fb122d765
vardask[0] sum 14416.1
vardata[1] sum 14416.1, name from-array-a1d722948a08ee25f34c508fb122d765
vardask[1] sum 14416.1
```
The two elements of the list are different, yet they got assigned the exact same name by dask. When the stack step happens, the first value is apparently overwritten by the second one, because they have the same name.

I was able to fix this in xgcm/xgcm#9 by assigning a custom ``name`` attribute when calling ``da.from_array``. But it seems like dask should automatically be choosing a unique name.

**Comment by mrocklin** [comment]
Dask.array determines keynames by hashing down the contents of the array (see https://github.com/blaze/dask/blob/master/dask/base.py#L176-L189).

So if two of your input arrays have the same content (e.g. same values, shape, strides, dtype) then they will be mapped to the same key.

In principle this shouldn't affect correctness at all.  Here is a small example.

```python
In [1]: import numpy as np
In [2]: x = np.ones((3, 3), dtype='f8')  # we'll reuse these twice
In [3]: y = np.random.random((3, 3))

In [4]: import dask.array as da
In [5]: arrays = [da.from_array(arr, chunks=arr.shape) for arr in [x, y, x, y]]
In [6]: X = da.stack(arrays, axis=0)

In [7]: X
Out[7]: dask.array<stack-b..., shape=(4, 3, 3), dtype=float64, chunksize=(1, 3, 3)>

In [8]: X.dask
Out[8]: 
{'from-array-e8122f0f6208166b3fda69f5ce877778': array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]),
 ('stack-bce041198f326d03aa91a3efe5d308b3',
  1,
  0,
  0): (<function dask.array.core.getarray>, ('from-array-aef6142b7e21f5c857c622429c2d672f',
   0,
   0), (None, slice(None, None, None), slice(None, None, None))),
 ('stack-bce041198f326d03aa91a3efe5d308b3',
  2,
  0,
  0): (<function dask.array.core.getarray>, ('from-array-e8122f0f6208166b3fda69f5ce877778',
   0,
   0), (None, slice(None, None, None), slice(None, None, None))),
 'from-array-aef6142b7e21f5c857c622429c2d672f': array([[ 0.66002451,  0.69792289,  0.72803412],
        [ 0.17911087,  0.74160782,  0.93489879],
        [ 0.42279052,  0.6404918 ,  0.2672002 ]]),
 ('stack-bce041198f326d03aa91a3efe5d308b3',
  3,
  0,
  0): (<function dask.array.core.getarray>, ('from-array-aef6142b7e21f5c857c622429c2d672f',
   0,
   0), (None, slice(None, None, None), slice(None, None, None))),
 ('from-array-aef6142b7e21f5c857c622429c2d672f',
  0,
  0): (<function dask.array.core.getarray>, 'from-array-aef6142b7e21f5c857c622429c2d672f', (slice(0, 3, None),
   slice(0, 3, None))),
 ('from-array-e8122f0f6208166b3fda69f5ce877778',
  0,
  0): (<function dask.array.core.getarray>, 'from-array-e8122f0f6208166b3fda69f5ce877778', (slice(0, 3, None),
   slice(0, 3, None))),
 ('stack-bce041198f326d03aa91a3efe5d308b3',
  0,
  0,
  0): (<function dask.array.core.getarray>, ('from-array-e8122f0f6208166b3fda69f5ce877778',
   0,
   0), (None, slice(None, None, None), slice(None, None, None)))}

In [9]: X.visualize(filename='X.png')
```

![x](https://cloud.githubusercontent.com/assets/306380/11126187/9d413662-8922-11e5-868f-310df0625e6d.png)

```python
In [10]: x.sum() * 2 + y.sum() * 2
Out[10]: 28.544163038481074

In [11]: X.sum().compute()
Out[11]: 28.544163038481074
```

So anyway, that's why this *shouldn't* be a problem.  Of course, apparently it is.  My guess is that some particular array function is failing handle repeat keys well.  Do you have any other information on when you get wrong results?

**Comment by rabernat** [comment]
Thanks for this great explanation. It seems like the hashing is not picking up on the difference between the two arrays.

> Do you have any other information on when you get wrong results?

It is a really intermittent problem. I will try to narrow it down further.

**Comment by mrocklin** [comment]
It would be valuable to see which arrays collide.

```python
from toolz import groupby
from dask.base import tokenize

groups = groupby(tokenize, arrays)
collisions = {k: v for k, v in groups.items() if len(v) > 1}
```

**Comment by shoyer** [comment]
I think the trouble is relying `repr` to be uniquely identifying for custom array objets. It probably would be a better idea to default to using some sort of unique ID for each array. Here's a concrete example of what can go wrong if two arrays shares the same repr:
```python
import numpy as np
from dask.base import tokenize

class CustomArray(object):
    def __init__(self, array):
        self.array = array
    def __getitem__(self, key):
        return self.array[key]
    @property
    def shape(self):
        return self.array.shape
    def __repr__(self):
        return repr(self.array)

# x is bigger than the amount of data numpy prints by default
x = np.zeros((1000, 1000))
y = x.copy()
y[500, 500] = 1

print tokenize(x)  # 0628ea46aa6e487c0329f05a0829d567
print tokenize(y)  # 82d43a740f5d20ac3fe4109514025bd2
print tokenize(CustomArray(x))  # 419522e29fc54c6d89e1f73bd5e2ee85
print tokenize(CustomArray(y))   # 419522e29fc54c6d89e1f73bd5e2ee85
```

Notice that the last two examples have the same token, even though they have different values!

**Comment by mrocklin** [comment]
Oh, we're not using numpy arrays then but some special class?  For ideal hashing support you would want to extend tokenize to that special class (see the example above for ndarrays).

Given that this is unlikely to happen in all cases then maybe `tokenize` should default to creating a `uuid` for safety's sake.

**Comment by shoyer** [comment]
@rabernat is loading data from disk in some custom serialization format (equivalent to mmap?) so it's not really feasible to hash each array before putting it in dask -- that would sort of defeat the point of using dask for out of core :). I agree that defaulting to a unique ID would be a good idea for unrecognized classes.

**Comment by mrocklin** [comment]
In cases like this I usually tokenize by the filename and the modification time.  If this is a format you're likely to use a fair amount going forward then it might be worth specifying this directly.

I'll swap out the default behavior for tokenize in a bit.

**Comment by rabernat** [comment]
Yes, @shoyer is exactly right: I am not wrapping a numpy array but rather something a bit funkier:

```python
class MDSArrayWrapper(NDArrayMixin):
    def __init__(self, array):
        self.array = array

    @property
    def dtype(self):
        dtype = self.array.dtype
```

I frankly have no idea whether this makes much sense, but it is more-or-less copied from xray.

**Comment by mrocklin** [comment]
OK.  https://github.com/blaze/dask/pull/830 should resolve your particular problem.

If you wanted to make this type play nicely with the tokenization bits of dask you could implement something like the following

```python
from dask.base import normalize_token

@partial(normalize_token.register, MDSArrayWrapper)
def normalize_MDSArray(a):
    return normalize_token(a.array)
```

In the naive case this won't have any effect though and the PR mentioned above should resolve your issue if you're on master

**Comment by shoyer** [comment]
As a side note, it would probably be a good idea for dask to explicitly
*exclude* memory mapped ndarrays from having their contents hashed. That
would almost certainly be undesired behavior. In this case I do think
creating explicit tokens based on last modified time and filename would be
the right choice, per Matthew's recommendation.
