### ISSUE TITLE
Revert list -> iterator behavior

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#832]
Currently lists have a special meaning in dask graphs as iterators

```python
In [1]: import dask

In [2]: dask.get({'x': (type, [])}, 'x')
Out[2]: generator
```

Historically this happened to support streaming reads out of on-disk storage for dask.array.  After https://github.com/blaze/dask/pull/822 this is maybe no longer as critical.  Also this change causes a few inconvenient ripples throughout the rest of dask.

Perhaps its time to revert this decision, so that lists are interpreted literally.  We could optionally have a special `Iterator` type, but I'd be in favor of dropping the streaming operation altogether for a while and see how things work out.  @shoyer can you think of any workflows in xray that might be adversely affected by this choice?

**Comment by shoyer** [comment]
Nothing strikes me off hand. This seems like a pretty sensible simplification.
