### ISSUE TITLE
Other Language Bindings

### ISSUE THREAD

**Issue by sirinath** [blaze/dask#836]
Can you provide binds for other languages?

**Comment by mrocklin** [comment]
What functionality are you looking for in particular.  Which parts of dask?

**Comment by sirinath** [comment]
I am looking for a task scheduling, data flow computing framework with API binds to JVM and .Net languages. The execution of the pipeline need not be in JVM or .net code but just the setting up, unless the tasks are written in a JVM or .net language.

**Comment by mrocklin** [comment]
Hrm, this isn't on my personal priority list, but I'd be happy to provide support if someone else wanted to take it on.

Alternative solutions might include:

1.  The scheduling algorithms within dask could be rewritten in other systems
2.  One could presumably find a data flow computing framework within the JVM / .NET ecosystems?
