### ISSUE TITLE
Delta memory usage in memory profiler

### ISSUE THREAD

**Issue by koverholt** [blaze/dask#840]
In the memory profiler, would it make sense to subtract off the initial memory usage when the context manager is initialized?

In the below screenshot, I'm running the profiler after doing other things in the notebook, and I'm only interested in the delta memory usage (~120 MB here), similar to the delta memory usage reported by [ipython_memwatcher](https://github.com/FrancescAlted/ipython_memwatcher).

<img width="792" alt="screen shot 2015-11-19 at 10 15 31 pm" src="https://cloud.githubusercontent.com/assets/303236/11291841/110f6210-8f0b-11e5-8823-d1d85e18ac0e.png">

**Comment by mrocklin** [comment]
This seems useful to me.  An alternative (though not necessarily better) approach would be to keep the numbers as they are, but change the default plotting range.
