### ISSUE TITLE
Add drop_duplicates' subset kwarg for parity with pandas

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#845]
Adding this makes the `Distinct` expression in blaze work easily. This came up while working on adding dask.dataframe to blaze in [this PR](https://github.com/blaze/blaze/pull/1317). This should be pretty easy.

Relevent blaze code:
https://github.com/blaze/blaze/blob/master/blaze/compute/pandas.py#L216

Relevant dask code:
https://github.com/blaze/dask/blob/master/dask/dataframe/core.py#L244

Pandas API reference:
http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.drop_duplicates.html

**Comment by mrocklin** [comment]
Agreed that this should be pretty easy.  I think you can probably just pass through the argument directly to the per-partition functions.

**Comment by mrocklin** [comment]
I'll do this in about an hour if no one beats me too it first.
