### ISSUE TITLE
Concatenate problem with HDF5?

### ISSUE THREAD

**Issue by CharlieLaughton** [blaze/dask#849]
I have two dask arrays created from data in two, different, hdf5 files:
```
f1 = h5py.File('x1.hdf5', "r")
f2 = h5py.File('x2.hdf5', "r")
x1 = f1["x"]
x2 = f2["x"]
da1h = da.from_array(x1, chunks=(2,2))
da2h = da.from_array(x2, chunks=(2,2))

print da1h.compute()
print da2h.compute()

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
```
Now I concatenate them:
```
xch = da.concatenate([da1h, da2h], axis=0)
print xch.shape
print xch.compute()
(8, 4)
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
```
Am I doing something silly?

**Comment by mrocklin** [comment]
This looks like a tokenization issue.  it arises because both `x1` and `x2` repr the same.  I'll fix this in master shortly.

If you want an immediate fix you can supply names directly like the following:

```python
da1h = da.from_array(x1, chunks=(2,2), name='x1')
da2h = da.from_array(x2, chunks=(2,2), name='x2')
```

**Comment by mrocklin** [comment]
Turns out this is already resolved in master.  PR containing test https://github.com/blaze/dask/pull/850

**Comment by mrocklin** [comment]
Text from the previous PR that resolved this issue recently

> Previously we used repr as a catch-all for tokenize. This failed
when different objects repred identically. Now we default to random
uuids. This requires us to be more diligent in the simple case but
makes us much more conservative about avoiding collisions.

**Comment by CharlieLaughton** [comment]
Thanks for your help – I was using the version from pip install. I have just cloned the repository and installed, now all looks fine.
