### ISSUE TITLE
converting strings to timestamps

### ISSUE THREAD

**Issue by fjanoos** [blaze/dask#863]
Hi, 
I have a dask dataframe with a 'time' column that in string format. I'm trying to convert it to a pandas Timestamp type as follows:
```
from pandas.tseries.tools import to_datetime
my_ddf['time'].map_partitions(to_datetime, columns='time').compute()
```
This conversion takes forever to run (>1min) . Running to_datetime on a pandas dataframe version of the data finishes in about 10 secs. Any suggestions about what's going on and how I can speed it up?

**Comment by mrocklin** [comment]
You seem to be doing the correct thing as far as I can see.  Perhaps try out the `Profiler` to see what is taking up the most time?

http://dask.pydata.org/en/latest/diagnostics.html#profiler

**Comment by mrocklin** [comment]
It could be that `to_datetime` doesn't release the GIL (most things coming from strings don't) and the threads are thrashing performance a bit.  What happens when you use a single thread

    my_ddf['time'].map_partitions(to_datetime, columns='time').compute(get=dask.async.get_sync)

**Comment by fjanoos** [comment]
The profiler results for the multithreaded version:
![image](https://cloud.githubusercontent.com/assets/923438/11608955/5bbd02e4-9b46-11e5-80ee-7d35e48cd6fc.png)

The single threaded version is somewhat faster, but still nowhere as fast as doing this on a pandas dataframe:
dask: 3min 26.1s
pandas: 623us.

Any ideas of where the overhead is ?

**Comment by mrocklin** [comment]
And, to be clear, if you hover over one of those green bars it says that the function is `to_datetime`, yes?

**Comment by mrocklin** [comment]
If so the next thing I would try is to use the single-threaded scheduler and use a standard Python profiler like the `profile` module or the `%prun` magic within IPython

    %prun my_ddf['time'].map_partitions(to_datetime, columns='time').compute(get=dask.async.get_sync)

**Comment by fjanoos** [comment]
The breakdown from the profiler is as expected:

```
      158853141 function calls (158852161 primitive calls) in 299.647 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        5   42.039    8.408  299.277   59.855 {built-in method array_to_datetime}
  3945396   36.804    0.000   80.065    0.000 _strptime.py:298(_strptime)
  7890792   36.148    0.000   47.709    0.000 parser.py:50(get_token)
   986349   35.967    0.000  138.039    0.000 parser.py:445(_parse)
   986349   12.022    0.000  166.749    0.000 parser.py:343(parse)
   986349   10.858    0.000   72.076    0.000 parser.py:173(split)
 21699788    7.994    0.000    7.994    0.000 {method 'read' of '_io.StringIO' objects}
```

**Comment by mrocklin** [comment]
And presumably something like this is fast?

    my_ddf['time'].compute(get=dask.async.get_sync).to_datetime()

**Comment by fjanoos** [comment]
Yes - I think that's probably what I'll have to do.

```
%time to_datetime(dask_df['time'].compute(), format="%Y%m%d %H:%M:%S.%f" )

%time to_datetime(pandas_df.time, format="%Y%m%d %H:%M:%S.%f")
```

```
CPU times: user 8.66 s, sys: 128 ms, total: 8.79 s
Wall time: 8.72 s
CPU times: user 8.34 s, sys: 4 ms, total: 8.35 s
Wall time: 8.31 s
```

**Comment by mrocklin** [comment]
Can you give me a reproducible example that I can play with locally?  I'd like to get to the bottom of this.

**Comment by fjanoos** [comment]
Can I share an hdf5 file with you ?

**Comment by fjanoos** [comment]
```
from pylab import *
import numpy as np
import matplotlib as npl
from random import sample
from imp import reload

import pandas as pd
from pandas import *
import dask.dataframe as ddf

n = 9e6
lts = date_range( '20150101', periods=n, freq='1D')

mydf = DataFrame( 
    dict(
        date=lts.strftime('%Y-%m-%d'), 
        ts=lts.astype(int64),
    )#,
    #index=lts
)
mydf['row_num'] = range(len(mydf))

my_ddf = ddf.from_pandas(mydf, npartitions =  10)
   
my_ddf['date'].map_partitions(to_datetime, columns='date').compute(get=dask.async.get_sync)
```

**Comment by mrocklin** [comment]
I'm not seeing the same performance degredation.  I'd be happy to receive a file that fits within an e-mail at mrocklin with the domain name `continuum.io`.  Also happy to connect to some other convenient data source somewhere.

```python
In [1]: import dask

In [2]: import numpy as np

In [3]: import pandas as pd

In [4]: n = 9e6

In [5]: lts = pd.date_range( '20150101', periods=n, freq='1D')

In [6]: mydf = pd.DataFrame( 
    dict(
        date=lts.strftime('%Y-%m-%d'), 
        ts=lts.astype(np.int64),
    ), 
)

In [7]: mydf['row_num'] = range(len(mydf))

In [8]: import dask.dataframe as dd

In [9]: my_ddf = dd.from_pandas(mydf, npartitions =  10)

In [10]: %time _ = pd.to_datetime(mydf.date)CPU times: user 11 ms, sys: 3.71 ms, total: 14.7 ms
Wall time: 14.5 ms

In [11]: %time _ = my_ddf.date.map_partitions(pd.to_datetime, columns='date').compute(get=dask.async.get_sync)
CPU times: user 54.4 ms, sys: 678 µs, total: 55.1 ms
Wall time: 53.9 ms

In [12]: %time _ = my_ddf.date.map_partitions(pd.to_datetime, columns='date').compute(get=dask.async.get_sync)
CPU times: user 20.4 ms, sys: 32 µs, total: 20.4 ms
Wall time: 19.9 ms
```

**Comment by fjanoos** [comment]
Is it possible that I was experiencing these delays because the dataframe I was using was backed by a csv file and memoized using joblib's memory package ?

**Comment by fjanoos** [comment]
@mrocklin 

Regarding my original fix for this problem, I'm running into a new issue. Specifically, this was my approach of converting time-strings in `fix_ddf` into pandas Timestamp objects by adding a new column :

``` python
# fix_ddf is the dataframe with string time stamps
print (fix_ddf.divisions, fix_ddf.npartitions, len(fix_ddf.divisions) )
time_col = to_datetime(fix_ddf['time'].compute(), format="%Y%m%d %H:%M:%S.%f" )
new_ddf = fix_ddf.assign(__datetime__=time_col, __timestamp__=time_col.astype(int64) )
print (new_ddf.divisions, new_ddf.npartitions, len(new_ddf.divisions) ) 
```

This the output of the print statements:
```
(0, 222299, 460136, 694275, 926828, 1159470, 1401018, 1645870, 1896652, 1924537) 9 10
(0, 222299, 460136, 694275, 926828, 1159470, 1401018, 1645870, 1896652, 1924536, 1924537) 10 11
```
For some reason, the number of partitions has increased by 1. Also, I can no longer index into the last partition ie. any index > 1924535 throws an IndexError.

Any ideas of what's going on ?

**Comment by mrocklin** [comment]
> Is it possible that I was experiencing these delays because the dataframe I was using was backed by a csv file and memoized using joblib's memory package ?

Perhaps you were including the cost to read the CSV file in your measurement of the dask.dataframe time while, with Pandas, the dataframe was already in memory?

**Comment by mrocklin** [comment]
With the divisions problem it will be much easier to diagnose the issue you're seeing if you're able to produce an example that I can reproduce locally.

It's odd to call compute and then assign the pandas dataframe into a dask.dataframe.  It works, it just feels somewhat inefficient. 

A simple toy example shows no problem here.  

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: df = pd.DataFrame({'x': [1, 2, 3, 4]})

In [4]: ddf = dd.from_pandas(df, npartitions=2)

In [5]: ddf2 = ddf.assign(y = pd.Series([10, 20, 30, 40]))

In [6]: ddf2
Out[6]: dd.DataFrame<elemwise-2a1ff96d6fc0f5d54ff67a316d1b81c0, divisions=(0, 2, 3)>

In [7]: ddf2.compute()
Out[7]: 
   x   y
0  1  10
1  2  20
2  3  30
3  4  40
```

Again, a reproducable example would be highly valuable.

**Comment by fjanoos** [comment]
I also don't have any problems when convering pandas dataframes to dask frames. 

The problems start to show up when using creating a dask graph for *datasets > 30mn rows*, with more than 10 partitions. 

It's all ok for smaller sizes.

If you recollect from another thread, I was trying read in a streaming data-source via subprocess pipes, but the problem also occurs when I try to read in a sufficiently large CSV file (>20GB). I have a feeling that I'm not creating the graph correctly and if you have any leads - that would be appreciated. In the meanwhile, I'll try to set up a way to transfer my dataset.

```python
import pandas as pd
from joblib import Parallel, delayed, Memory

__memorycache__ = Memory( cachedir='/dev/shm/dask/', verbose=0 )

# dcr.get_pipe() returns an open subprocess pipe object over a particular date range. You can point it to a csv file.
@__memorycache__.cache
def cache_read_csv(pipe, start, end, div):
    if dcr.__verbose__: print('reading from ', start, ' to ', end)
    df = pd.read_csv( dcr.get_pipe(start, end), parse_dates='time' )
    return df;


def __fix__( df , seix):
    '''
    :param dv Take as input a dask action tuple that encapsulates a dataframe.
    :param seix: Tuple of start and end indices
    Use dask imperative to execute that tuple.
    Thunk it's indices based on start and end indices
    '''
    df.index = range( seix[0], seix[1] )
    return df;

raw_dsk = {  ('ddf', i): (cache_read_csv, dcr, start, end, i) for i, (start, end) in enumerate(date_range)   }

ddf_divisions = [0] + [None]*len(date_range)
cols = __diskcache_read_csv__(dcr, date_range[0][0], date_range[0][1], 0 ).columns
raw_ddf = ddf.DataFrame( raw_dsk, 'ddf', cols, ddf_divisions )

# fix the divisions values
partition_len = raw_ddf.map_partitions(len).compute() # has to scan through the data once...
ddf_divisions[1:] = cumsum( partition_len )
raw_ddf.divisions = tuple(ddf_divisions)

# construct a dict of division number and start and end indices
seix_map = dict( zip(range(raw_ddf.npartitions) , zip(ddf_divisions[0:-1], ddf_divisions[1:]) ) )

# 'fix the indices of the dataframe
fix_dsk = dict()
for dk in raw_dsk.keys():
            cdiv = dk[1]; # current division
            fix_dsk[('fix_ddf',cdiv)] = (__fix__, raw_dsk[dk], seix_map[cdiv] )
fix_ddf = ddf.DataFrame(fix_dsk, 'fix_ddf', cols, ddf_divisions);

# convert the string to datetime type. doing something like fix_df['time'].map_partitions(to_datetime) takes over 10 mins for 30mn rows
time_col = to_datetime(fix_ddf['time'].compute(), format="%Y%m%d %H:%M:%S.%f" )

#this assign adds one more division to the output frame and breaks  the dataframe.
return fix_ddf.assign(__datetime__=time_col, __timestamp__=time_col.astype(int64) );

```

**Comment by fjanoos** [comment]
I think I figured out the problem ... 

Wrong way to fix the division sizes:
``` python
partition_len = raw_ddf.map_partitions(len).compute() 
ddf_divisions[1:] = cumsum( partition_len )
raw_ddf.divisions = tuple(ddf_divisions)
```

Right way to fix the division sizes:
``` python
partition_len = raw_ddf.map_partitions(len).compute() 
ddf_divisions[1:] = cumsum( partition_len )
ddf_divisions[-1] -= 1 #  the last division is an inclusive index.
raw_ddf.divisions = tuple(ddf_divisions)
```

**Comment by mrocklin** [comment]
Ah ha, nice find!

**Comment by mrocklin** [comment]
Yes, that can easily be a gotcha, it's a bit unintuitive

**Comment by ricoms** [comment]
I see your codes, and none of those work for me:

```
ValueError: Metadata inference failed in `to_datetime`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ValueError('to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing')
```

How are those working without providing a `meta=` keyword?

**Comment by jsignell** [comment]
This is a very old issue. I recommend opening a new issue with a minimal reproducible example.
