### ISSUE TITLE
broadcast_chunks fails when first chunk is (1,)

### ISSUE THREAD

**Issue by ererkka** [blaze/dask#872]
It seems that dask.array.core.broadcast_chunks fails with when first chunk in input is (1,), even when they are identical. For example 
```python
>>> broadcast_chunks(((2,), (2, 2),), ((2,), (2, 2),))
((2,), (2, 2))
```
but
```python
>>> broadcast_chunks(((1,), (2, 2),), ((1,), (2, 2),))
ValueError: Chunks do not align: []
```
The cause is on line 604 in array/core.py:
```python
step2 = [c for c in step1 if c != (1,)]
```
Why the `if c != (1,)`?

**Comment by mrocklin** [comment]
This is intended to support [numpy-style broadcasting rules](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html#general-broadcasting-rules) between arrays with different numbers of dimensions.  It looks like we fail in the case where all arrays actually have a singleton dimension.  

This looks like a genuine bug to me.
