### ISSUE TITLE
unable to load a pickle file in dask dataframe

### ISSUE THREAD

**Issue by satya-panda** [blaze/dask#879]
when i am trying to create a dask dataframe by reading a pickle file , i am getting an error

import dask.dataframe as dd
df = dd.read_pickle("D:\test.pickle")

AttributeError: 'module' object has no attribute 'read_pickle'

but  it works fine with read_csv
And in pandas it was successful as usual.

So please correct me if i am doing something wrong there or in dask we can't create dataframe by reading a pickle file at all.

**Comment by mrocklin** [comment]
You're not doing anything wrong.  dask.dataframe doesn't yet have a `read_pickle` function.  Please note that dask.dataframe does not reimplement all of pandas functionality.

If you have a pandas pickle file perhaps you can read the data into memory with pandas and then use `dd.from_pandas`?

    df = pd.read_pickle(...)
    ddf = dd.from_pandas(df, npartitions=10)

Why do you want to use dask.dataframe if your data already fits into memory?

**Comment by satya-panda** [comment]
Actually the pickle file is really a large sized one.And there are multiple/complex operation/filteration has to be applied on that dataframe. And i got to know about dask that  support parallel processing internally and merely uses pandas way of coding and operation.  following issue get me awareness about dask module
      http://stackoverflow.com/questions/34173859/filtering-a-large-dataframe-in-pandas-using-multiprocessing/34200141?noredirect=1#comment56177126_34200141

**Comment by mrocklin** [comment]
If you can fit the dataset into memory then in I recommend loading the data with `pandas.read_pickle` and then wrapping `dask.dataframe` around that `pandas` dataframe with `dask.dataframe.from_pandas`

    df = pd.read_pickle(filename)  # read from pickle with pandas
    ddf = dd.from_pandas(df, npartitions=10)  # split with dask.dataframe

    result = ddf.query(...)[...]  # do filtering operations on dask dataframe
    result = result.compute()  # perform computation in parallel, convert back to pandas
    result.to_csv(...)

**Comment by mrocklin** [comment]
Closing this.  There is unfortunately no easy way to stream through a pickle file.

**Comment by About9** [comment]
It will be very helpful if dask provides a function like dask.dataframe.read_pickle('*.pkl').
read_csv is very time-consuming in pandas (5-10 times slower than read_pickle).

**Comment by TomAugspurger** [comment]
@About9 you can probably write your own helper using `dask.delayed`, `dd.from_delayed` and `dd.concat` to do this. I'm not sure it warrants its own method.

**Comment by mrocklin** [comment]
https://docs.dask.org/en/latest/dataframe-create.html#dask-delayed
