### ISSUE TITLE
API/BUG: array.map_blocks raises IndexError for 0-dim array

### ISSUE THREAD

**Issue by sinhrks** [blaze/dask#884]
I understand ``map_blocks`` can work for function which returns scalar as below.

```
import numpy as np
import dask.array as da

darr = da.from_array(np.array([1, 2, 3, 4]), chunks=2)

def f(x):
    return 1

darr.map_blocks(f).compute()
# array([1, 1])
```

However, it may raises ``IndexError`` in ufuncs, which returns 0-dim array. Should it be handled like scalar, or raise understandable error message?

```
darr.map_blocks(np.sum).compute()
# IndexError: tuple index out of range

def h(x):
    return np.array(1)

darr.map_blocks(h).compute()
# IndexError: tuple index out of range

# Specifying chunks doesn't solve the problem
darr.map_blocks(h, chunks=(1, )).compute()
# IndexError: tuple index out of range
```

**Comment by mrocklin** [comment]
Map_blocks still expects the function to return a numpy array with the same dimension as the output dask array.  

```python
In [3]: darr = da.from_array(np.array([1, 2, 3, 4]), chunks=2)

In [4]: def f(x):
   ...:     return np.array([1])
   ...: 

In [5]: darr.map_blocks(f).compute()
Out[5]: array([1, 1])
```

The recent changes to map_blocks allows the output dimension of the dask array to differ from the input dimension of the dask array.

However, we could support what is desired here fairly easily in the common case.  In principle we could wrap the output of the block function with the following function:

```python
def at_least_n_dimensions(n, arr):
    arr = np.asanyarray(arr)
    while arr.ndim < n:
        arr = arr[None, :]
```

In practice though I expect it will be a bit more difficult, especially if the user wants to specify which dimensions should be added through the `chunks=` input.

**Comment by sinhrks** [comment]
Thanks, I understand it can't be full-automatic.  

My question here whether to regard 0-dim array like scalar, currently ``Dask`` doesn't have any logic to handle it properly.

```
np.array(1)
# array(1)
np.array(1).ndim
# 0
np.array(1).shape
# ()
```

**Comment by mrocklin** [comment]
Sorry for the delay.  Dask.array can handle zero-dimensional arrays

```python
In [1]: import dask.array as da

In [2]: x = da.ones(5, chunks=(2,))

In [3]: y = x[3]

In [4]: y
Out[4]: dask.array<getitem..., shape=(), dtype=float64, chunksize=()>

In [5]: y.shape
Out[5]: ()

In [6]: y.ndim
Out[6]: 0
```

The problem here is that the output of the function `f` must have the same dimension as the output array.  

In this case the input and output dask array have dimension 1, so the function `f` should return an array of dimension 1.

darr = da.from_array(np.array([1, 2, 3, 4]), chunks=2)  # ndim == 1
darr.map_blocks(f)  # ndim == 1

In this case though the function f returns an array of dimension 0

```python
def f(x):
    return 1  # ndim == 0
```

**Comment by mrocklin** [comment]
@sinhrks does the explanation above make sense?  Can this be closed?

**Comment by sinhrks** [comment]
Thanks for the answer. I expect 0-dim array and scalar should work the same, but not have an immediate needs. Let me close once and will issue another if needed in future.
