### ISSUE TITLE
Cummulative numpy functions for Dask Arrays

### ISSUE THREAD

**Issue by pwolfram** [blaze/dask#923]
Are cumulative numpy functions available for Dask Arrays?

It does not appear that the cumulative functions, e.g., np.cumsum, are available: https://github.com/blaze/dask/blob/master/dask/array/core.py#L1052-L1179 for dask Arrays.  Is there a particular reason why this is the case?  I'd like to be able to do computations of the form

```
import dask.array as da                     
import numpy as np                          
x = da.from_array(np.random.rand(10,10),chunks=(2,5))  
x.cumsum(axis=1)                                  
```
Currently this does not appear to be supported.

**Comment by mrocklin** [comment]
Looks like they're not around now.  No fundamental reason why they wouldn't be doable though.

**Comment by pwolfram** [comment]
Thanks @mrocklin!

**Comment by pwolfram** [comment]
This issue is now covered by PR #925 and am closing it in anticipation.
