### ISSUE TITLE
Some notes about trying to use dask.array for sparse matrices.

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#928]
I was working on some sparse matrix datastructures which used dask.arrays internally. Then I realized that dask.array was basically to restrictive for my approach. Notes on this are [here](https://github.com/cowlicks/spoorcellel#update----why-this-implementation-wont-work). They might be useful if y'all consider doing sparse matrix stuff in the future.

**Comment by mrocklin** [comment]
That's an interesting analysis and yes, that does make sense.  Thanks for the heads up.

It's not clear to me how best to do sparse matrices.  My guess is that it depends on the algorithm you would want to implement.

**Comment by alimanfoo** [comment]
FWIW I found working with sparse genetic data that using chunked arrays
with compression via zlib or lz4 uses less memory than a sparse matrix
representation such as CSR. Compressed chunked arrays also play very
naturally with dask, and chunks can be persisted to disk. Obviously mileage
will vary depending on data and computations needed.

On Tuesday, 19 January 2016, Matthew Rocklin <notifications@github.com>
wrote:

> That's an interesting analysis and yes, that does make sense. Thanks for
> the heads up.
>
> It's not clear to me how best to do sparse matrices. My guess is that it
> depends on the algorithm you would want to implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blaze/dask/issues/928#issuecomment-172915223>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by mrocklin** [comment]
Closing for now.  Feel free to reopen if there is work to be done.
