### ISSUE TITLE
ndslice missing?

### ISSUE THREAD

**Issue by markiemarkus** [blaze/dask#952]
Am trying to run the simple example here
https://anaconda.org/dask/simple-numpy-sum/notebook

I had a fresh install of anaconda for my python environment and dask: 0.7.6-py27_0 is installed via conda install dask

However ndslice can not be found,

from dask.array import ndslice
ImportError                               Traceback (most recent call last)
<ipython-input-10-c41955e066c2> in <module>()
----> 1 from dask.array import ndslice
      2 
      3 ndslice(x, (10,), 4)  # with blocks of size ten, get the fourth

ImportError: cannot import name ndslice

I have confirmed that other items/namespaces in dask exist but I can not see this ndslice anywhere.

**Comment by mrocklin** [comment]
This notebook is very very old.  Actually I wasn't aware that it existed so we should probably delete it.  @chdoig I think that you put these up here.  Does anyone have the bandwidth to maintain these properly?  If not then can we take them down?

@markiemarkus if you're looking to get your feet wet with dask I recommend the [dask tutorial](https://github.com/blaze/dask-tutorial).

**Comment by markiemarkus** [comment]
That explains a fair bit!

**Comment by chdoig** [comment]
@mrocklin, I've tested the notebooks. I have deleted simple-numpy-sum and humble-demo from: https://anaconda.org/dask. I left parallelize_image_filtering_workload and using-dask-and-anaconda-cluster-to-analyze-data-on-an-ec2-cluster, since they are referenced in blogposts and run.

**Comment by mrocklin** [comment]
Thanks!
