### ISSUE TITLE
Install toolz via dask?

### ISSUE THREAD

**Issue by alimanfoo** [blaze/dask#962]
Toolz is a dependency but is not installed automatically when dask is installed via pip. This has caused some confusion/inconvenience. Is there a reason?

**Comment by mrocklin** [comment]
You probably want to `pip install` or depend upon  `dask[array]` rather than `dask`

The core dask scheduler is stdlib only.  Each collection has some exotic dependencies.  We didn't want one class of users to have to install another class's tools.

**Comment by mrocklin** [comment]
Here is the relevant line in setup.py

```
extras_require = {
  'array': ['numpy', 'toolz >= 0.7.2'],
  'bag': ['cloudpickle', 'toolz >= 0.7.2', 'partd >= 0.3.2'],
  'dataframe': ['numpy', 'pandas >= 0.16.0', 'toolz >= 0.7.2', 'partd >= 0.3.2'],
}
extras_require['complete'] = sorted(set(sum(extras_require.values(), [])))
```

**Comment by alimanfoo** [comment]
Thanks, will do. Maybe make this super clear in the docs?

On Sunday, 7 February 2016, Matthew Rocklin <notifications@github.com>
wrote:

> You probably want to pip install or depend upon dask[array] rather than
> dask
>
> The core dask scheduler is stdlib only. Each collection has some exotic
> dependencies. We didn't want one class of users to have to install another
> class's tools.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blaze/dask/issues/962#issuecomment-180925460>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by mrocklin** [comment]
Current content is here: http://dask.readthedocs.org/en/latest/install.html#install-parts-of-dask

We should probably make this more prominent, or suggest `pip install dask[complete]` as default

**Comment by alimanfoo** [comment]
Yes I'd suggest either replace "pip install dask" with "pip install
dask[complete]" in current doc structure or delete "pip install dask" and
merge with subsection below to make the list of [] install options the
first thing the reader comes across.

On Sunday, 7 February 2016, Matthew Rocklin <notifications@github.com>
wrote:

> Current content is here:
> http://dask.readthedocs.org/en/latest/install.html#install-parts-of-dask
>
> We should probably make this more prominent, or suggest pip install
> dask[complete] as default
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blaze/dask/issues/962#issuecomment-180928160>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721
